### ISSUE TITLE
run matterhorn cleanup script to free up alps space

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#10]
2.4 tb is currently being eaten up by matterhorn files which can be cleaned up per conversation in #4 .

Please run investigate and run 

https://wiki.dlib.indiana.edu/display/VarVideo/Maintaining+Matterhorn+Disk+Space

per MBK.

**Comment by Toputnal** [comment]
Has been run.  We now have 50% free on the Dropbox share.  We are still discussing the remaining 1.8 TB of data that the script did not delete and which dates as far back as 2014.

**Comment by davidschober** [comment]
Great news. Thanks team. Keep us posted.
