### ISSUE TITLE
Embed doesn't work in Firefox

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#100]
Embedding a public object does not work in Firefox on either Mac or PC.

URL https://www.w3schools.com/html/tryit.asp?filename=tryhtml_intro

Embed info
        <iframe title="Northwestern Football Preview, 1955 - 1955 Football Preview" src="http://hdl.handle.net/2166.MEDIA/j92g257m7h" width="600" height="450" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      
Does not show up at all.

**Comment by carrickr** [comment]
Handles need to be updated so this doesn't work in any browser right now it seems, however the moment we do that we have a hard cut over to Avalon 6.  So we probably want to do handles at the same time we do Ares, production Canvas, etc.

**Comment by carrickr** [comment]
#126 supersedes this
