### ISSUE TITLE
List of services we need to cut over 

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#101]
- handles changeover (Carrick: will happen automagically when we change DNS)

- notify Course Reserves/MADS about downtime and wonkiness of systemn during proposed downtime Monday, June 12 8:30-1

- put notice on front page about downtime -similar to ```The Repository | Images website will undergo maintenance on Tuesday June 13th from 9am - 11am. The website will be unavailable during this time.```

**Comment by ccaizzi** [comment]
@jenyoung i think we can close this--we have a DNS ticket and a notice ticket and I informed Molly and Cecile.
