### ISSUE TITLE
Put Outage Notification up on the AVR Homepage

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#103]
Regarding the Monday DNS Switch.  Put this up on Thursday once dev-ops as confirmed in #102 they are good to go for Monday.

**Comment by carrickr** [comment]
Dev-ops is good with the Monday window, will do the message after backlog buddies

**Comment by carrickr** [comment]
@mbklein @ccaizzi 

This is live, any feedback on the message or design?  I was debating if a bold "Service Alert" head would be good or would just clutter up the homepage.

**Comment by ccaizzi** [comment]
@carrickr  can you make it read like Images' notice just for consistency sake? http://images.northwestern.edu/

**Comment by carrickr** [comment]
Changed
