### ISSUE TITLE
Create Cyberduck Script for RDC staff

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#105]
Everyone in RDC should have a script

http://www.library.northwestern.edu/about/contact/staff-directory.html#Repository_and_Digital_Curation

**Comment by davidschober** [comment]
@mbklein I think you created this script. Is it somewhere @carrickr  can grab next week to generate for these folks?

**Comment by carrickr** [comment]
I created it, mbk and I both have copies of it.  This can be done whenever depending on priority.

**Comment by davidschober** [comment]
OK. Lower priority. I just wanted to make sure we were ready.

**Comment by carrickr** [comment]
Yeah for now if anyone needs it, just ask.  It takes me literally a minute or two plus context switching cost.  I've just been focusing on bigger fish.

**Comment by carrickr** [comment]
Emailed Dan to see which members of his staff have an immediate need for credentials will mint those

**Comment by davidschober** [comment]
@jenyoung I'm going to close this, we can get creds as needed. @carrickr you're on call for this.

**Comment by carrickr** [comment]
Reopening as I got the three names:

Dan Zellner
NetID: dzellner
 
Liz Weinstein
NetID: Law9962
 
Josh Yocum
NetID: jmy5226

**Comment by carrickr** [comment]
Credentials emailed to all users
