### ISSUE TITLE
Add Help and About content and make homepage Thumbnails

### ISSUE THREAD

**Issue by ccaizzi** [nulib/avalon#106]
Make sure we have thumbnails on the homepage linking to content. 

- [x] Choose thumbnails for home page
- [x] put them on the homepage

**Comment by davidschober** [comment]
Rewriting, much of this was redundant with #62. This issue is just for adding thumbnails.

**Comment by davidschober** [comment]
Note, the issue with "about" is being tracked elsewhere.
