### ISSUE TITLE
Write D̶O̶I̶ ARK generator

### ISSUE THREAD

**Issue by mbklein** [nulib/avalon#108]
Add a Permalink handler to verify/create/update D̶O̶I̶s̶ ARKs through the EZID API.

**Comment by davidschober** [comment]
@mbklein can you pair up with someone working on hyrax? We have an outstanding issue to create DOIs. It'd be great if we could knock them both out.

**Comment by mbklein** [comment]
This is done-ish; I just have to turn it on by adding our EZID credentials and ARK shoulder to the environment config. I can show the rest of the team how to do this in about 3 minutes.

**Comment by davidschober** [comment]
K. so are we just waiting for a final word from someone or is this good to turn on?

**Comment by mbklein** [comment]
Waiting for word from John Dorr's email to Michael Witt (the EZID guy from Perdue)

**Comment by davidschober** [comment]
@mbklein when you get back from OR, let's figure out if we can port the work here to https://github.com/nulib/institutional-repository/issues/12

cc: 
@kdid @bmquinn

**Comment by mbklein** [comment]
DOI generator turned into an ARK generator. But it's done and configured and working.

**Comment by davidschober** [comment]
Nice, we should discuss ark vs doi with Diaz and dorr.

**Comment by ccaizzi** [comment]
@davidschober John was in the loop about this.  ARK is better for our digital collections.  ARCH content should be doi most likely.
