### ISSUE TITLE
Prepare to handle existing Handles

### ISSUE THREAD

**Issue by mbklein** [nulib/avalon#109]
Write before_filter to catch and redirect old PIDs, e.g.:

* Object route: `/media_objects/numedia:1028` should redirect to `/media_objects/rf55z773n`
* Section route: `/media_objects/numedia:1028/section/numedia:2153` should redirect to `/media_objects/rf55z773n/section/dr26xx694`
* Type-agnostic object route: `/objects/numedia:2153` should redirect to `/objects/dr26xx694`

**Comment by davidschober** [comment]
@mbklein it looks like this worked, correct? Should we go ahead and close.

**Comment by davidschober** [comment]
@carrickr @mbklein closing this, there's a hangeroner from embeds that I created here #127
