### ISSUE TITLE
Search Results Aren't Showing Title Properly

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#112]
http://avalon.repo.rdc.library.northwestern.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=johnny+cash

First result should be The Legend, not just The.  Title is set properly:

```
irb(main):014:0> MediaObject.find('pk02c977h').title
=> "The legend"
```

**Comment by davidschober** [comment]
This looks sorted now? Did the reindex help?

**Comment by davidschober** [comment]
![screen shot 2017-06-12 at 10 58 08 am](https://user-images.githubusercontent.com/4803230/27042935-178f6cf6-4f5e-11e7-9183-389b6e1b5a29.png)
