### ISSUE TITLE
trying to create a collection using the batch ingest spreadsheet should return an error

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#113]
trying to create a collection using the batch ingest spreadsheet should return an error

example: 
Collection name: [non-existing collection]
email address: [email]

user should get an email saying that the collection doesn't exist.

**Comment by davidschober** [comment]
Team, let's check this against Avalon proper to see if it's something we need to roll upstream .

**Comment by mbklein** [comment]
We ignore the name of the collection in the spreadsheet in favor of using the collection the dropbox folder is attached to.
