### ISSUE TITLE
Rename Avalon 4 to legacy.media...

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#114]
So JYo et al can still check data on it.  Current suggestion is legacy.media.library.northwestern.edu

**Comment by d-venckus** [comment]
This is done.  The address "legacy.media.library.northwestern.edu" is now a CNAME for avalonweb2.library.northwestern.edu.  

There are separate tickets to regenerate the ssl san certs to include the new name (#115) as well as to limit http/https access to NULib and sslvpn only (#116).
