### ISSUE TITLE
Regenerate ssl certs for legacy.media (avalonweb2p)

### ISSUE THREAD

**Issue by d-venckus** [nulib/avalon#115]
Having changed DNS for media.northwestern.edu to point to the new AWS pilot instance, we'll need to update the ssl certs on avalonweb2p to also recognize the new CNAME of legacy.media.library.northwestern.edu.

**Comment by d-venckus** [comment]
This is done.  I created and installed a SAN/multi-name SSL cert onto avalonweb2p, answering to both "avalonweb2p.library" and also "legacy.media.library".

**Comment by egspoony** [comment]
I have verified.
