### ISSUE TITLE
Logged Out Browsing Does Not Show Facets

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#119]
Visit media.northwestern.edu logged out, no facets are show.  Facets are visible when logged in.

<img width="1540" alt="screen shot 2017-06-12 at 12 34 23 pm" src="https://user-images.githubusercontent.com/5350060/27044677-6ac63a04-4f6c-11e7-8d6c-4b4f45c4ed06.png">
<img width="1529" alt="screen shot 2017-06-12 at 12 34 30 pm" src="https://user-images.githubusercontent.com/5350060/27044678-6accf628-4f6c-11e7-93da-6edcbff0a371.png">

**Comment by adamjarling** [comment]
@carrickr I noticed that when not logged in, no facets were displaying, and there was a big left-column gap on the home page.  So I put some code in the rails .erb file to check for the conditions where it seemed Facets are displayed from the Rails app.  If Facets are not being delivered by the app, I set the 'Sample Content' section to be full width.

**Comment by adamjarling** [comment]
Does that scenario of the app delivering Facets make sense?  Or is it expected behavior?

**Comment by carrickr** [comment]
there should be facets displaying in the future as we index in public data, if no facets are showing up because of all zero counts, that's a permissions problem mbk or I can check

**Comment by davidschober** [comment]
It's odd though, there are definitely public items showing.

**Comment by adamjarling** [comment]
I can pull back those changes, and the layout will just expect that the Facets sidebar will populate all the time.  That sound ok?
