### ISSUE TITLE
video won't stream in safari

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#121]
Some videos don't seem to be streaming in safari. 

For instance Serfs : shows a 0.00 end time.

HLS?

http://media.northwestern.edu/media_objects/t435gc96m

![screen shot 2017-06-12 at 11 51 02 am](https://user-images.githubusercontent.com/4803230/27045068-766a7106-4f65-11e7-86e2-b3692f08540f.png)

**Comment by carrickr** [comment]
MasterFile is: 6969z076v

Derivatives, Location and HLS Locations are are:
3c9a4707-00de-4cf7-ba66-b2ba5b8c0cf9
s3://avalon-derivatives-cfx3wj9/6969z076v/low/21422195320002441nongnu_disc1.mp4
s3://avalon-derivatives-cfx3wj9/6969z076v/low/hls/21422195320002441nongnu_disc1.m3u

60e1c7b9-4f40-44f9-8929-5d383c4635c9
s3://avalon-derivatives-cfx3wj9/6969z076v/medium/21422195320002441nongnu_disc1.mp4
s3://avalon-derivatives-cfx3wj9/6969z076v/medium/hls/21422195320002441nongnu_disc1.m3u8

da8c6107-b828-4365-94ef-7b7b8c71749a
s3://avalon-derivatives-cfx3wj9/6969z076v/high/21422195320002441nongnu_disc1.mp4
s3://avalon-derivatives-cfx3wj9/6969z076v/high/hls/21422195320002441nongnu_disc1.m3u8

**Comment by carrickr** [comment]
The derivatives exist, the .m3u8s do not exist

**Comment by carrickr** [comment]
@davidschober All three of these should stream in Safari now.

We will do #123 to handle the broader case, this will be a long running crawl
