### ISSUE TITLE
Embed doesn't work

### ISSUE THREAD

**Issue by egilchrist** [nulib/avalon#126]
Tested embed and couldn't run it.  Tested in both Chrome and Firefox.  
![screen shot 2017-06-12 at 2 20 13 pm](https://user-images.githubusercontent.com/20909880/27051109-89ab9bfe-4f7a-11e7-8ae0-701a6564a3a0.png)
![screen shot 2017-06-12 at 2 23 54 pm](https://user-images.githubusercontent.com/20909880/27051194-d7adf5b8-4f7a-11e7-8d05-94f1d472135a.png)

**Comment by davidschober** [comment]
Dupe of #127
