### ISSUE TITLE
Embedded videos on open door don't seem to be working

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#127]
## Description

Embedded videos are not working properly. They all have /embed as part of their extension and that seems to be causing them to fail. (removing the /embed resolves correctly)

e.g. http://media.northwestern.edu/master_files/numedia:40958/embed vs http://media.northwestern.edu/master_files/numedia:40958/

http://imaginationwithoutborders.northwestern.edu/about/
http://imaginationwithoutborders.northwestern.edu/about-jp/
http://imaginationwithoutborders.northwestern.edu/collections/revelation/
http://imaginationwithoutborders.northwestern.edu/collections-jp/revelation-jp/
 
http://opendoor.northwestern.edu/archive/items/show/354
http://opendoor.northwestern.edu/archive/items/show/353
http://opendoor.northwestern.edu/archive/items/show/352
http://opendoor.northwestern.edu/archive/items/show/351
http://opendoor.northwestern.edu/archive/items/show/349

**Comment by davidschober** [comment]
related to #126

**Comment by davidschober** [comment]
@carrickr

**Comment by ccaizzi** [comment]
when this is fixed, can you update Josh Honn @davidschober

**Comment by davidschober** [comment]
Of course

**Comment by davidschober** [comment]
@mbklein @carrickr This looks like the last big one...

**Comment by carrickr** [comment]
@mbklein 

we have a bunch of url append '/embed' calls in the code base, I can just remove all the append commands if we want to go that way.

I would note that we also can't embed via handle is not working either

```
        <iframe title=""A Gift from Somewhere" - AFR111_4.wav" src="http://hdl.handle.net/2166.MEDIA/900n79h82f" width="600" height="50" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
```

**Comment by carrickr** [comment]
![Screen Shot 2017-06-16 at 4.15.07 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57597a1ac08e191300f20ed2/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f56b7191a37cf1132e4f5f585ecc3c4a4356bcbbd671f3e57862804e0eead5380977903d14a9ed851beb03e8208f1a85b5b4894ad2f42f67b6d5db1063474f4dcbed5727a29a48cd5bfc4ae54452a2173262e57f3079408653.png)

**Comment by mbklein** [comment]
We have three issues here:

- [] The embed UI itself, which we're working on.
- [] Embed authentication, which I can work on while @adamjarling deals with the UI issue
- [] The inappropriate quoting in `<iframe title=""A Gift from Somewhere" - AFR111_4.wav" ...`

**Comment by ccaizzi** [comment]
@mbklein is the inappropriate quoting something we can deal with or is it from the external websites?
