### ISSUE TITLE
Broken thumbnail generation / Thumbnail generator produces a broken image

### ISSUE THREAD

**Issue by egilchrist** [nulib/avalon#128]
## Description:

Updating thumbnails on some existing pieces of media does not seem to work.

To recreate go to:

- http://media.northwestern.edu/media_objects/3197xm17m
- Try to update thumbnail
- note that the thumbnail generator is "Blank" or a "broken image"

**Comment by davidschober** [comment]
@egilchrist , can you give us the url? I'm thinking this might be the known bug where new videos have to have some non zero number for a thumbnail before you can use the button. (this is AWS specific)

**Comment by egilchrist** [comment]
This was the one where the thumbnail was showing up as broken and wouldn't change
http://media.northwestern.edu/media_objects/3197xm17m

**Comment by egilchrist** [comment]
This is the one I just ingested to test where it wouldn't let me click to create a thumbnail at all
http://media.northwestern.edu/media_objects/5h73pw048

**Comment by egilchrist** [comment]
This is the one where it won't give me the preview and won't save the changes to the pre-existing thumbnail
http://media.northwestern.edu/media_objects/gf06g273j

**Comment by davidschober** [comment]
@carrickr or @mbklein can yo look at this one... It seems very odd.

**Comment by davidschober** [comment]
@mbklein I'm still getting a broken image when trying to update a thumbnail on the example.

**Comment by mbklein** [comment]
I believe this is fixed now for new videos. Needs review and testing.

**Comment by jenyoung** [comment]
@mbklein was this tested?
