### ISSUE TITLE
Note cleanup for Marcellus Master Class

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#130]
These need to have a Note Type associated with the Note. 
Type=local

"numedia:1170"=>"j6731382c",
 "numedia:1175"=>"2227mp670",
 "numedia:1179"=>"br86b361k",
 "numedia:1183"=>"8w32r560x",
 "numedia:1187"=>"xp68kg25q",
 "numedia:1192"=>"47429919f",
 "numedia:1197"=>"j6731384x",
 "numedia:1202"=>"2f75r8056",
 "numedia:1207"=>"g445cd17d",
 "numedia:1212"=>"5999n343n",
 "numedia:1217"=>"fn106z01z",
 "numedia:1220"=>"pn89d6613",
 "numedia:1223"=>"cn69m417n",
 "numedia:1230"=>"0g354f27r",
 "numedia:1235"=>"s4655g60k",
 "numedia:1239"=>"2v23vt39w",
 "numedia:1242"=>"gb19f5828",
 "numedia:1247"=>"1544bp10f",
 "numedia:1250"=>"d217qp524",
 "numedia:1253"=>"wm117p00q",
 "numedia:1256"=>"wm117n995",
 "numedia:1259"=>"12579s31z",
 "numedia:1261"=>"gf06g270q",
 "numedia:1265"=>"5m60qr92x",
 "numedia:1268"=>"9w032305v",
 "numedia:1271"=>"w9505051c",
 "numedia:1275"=>"sx61dm295",
 "numedia:1278"=>"x346d4190",
 "numedia:1281"=>"g732d904k",
 "numedia:1283"=>"3n203z105",
 "numedia:1287"=>"7p88cg57g",
 "numedia:1290"=>"js956f82z",
 "numedia:1293"=>"xp68kg260",
 "numedia:1296"=>"3t945q80c",
 "numedia:1300"=>"st74cq49d",
 "numedia:1302"=>"k06987539",
 "numedia:1305"=>"qn59q401h",
 "numedia:1307"=>"cj82k7395",
 "numedia:1312"=>"c247ds16m",
 "numedia:1316"=>"c821gj859",
 "numedia:1318"=>"xs55mc06r",
 "numedia:1320"=>"x633f101s",
 "numedia:1326"=>"b2773v74n",
 "numedia:1332"=>"vd66vz88c",
 "numedia:1337"=>"df65v788h",
 "numedia:1342"=>"1v53jx087",
 "numedia:1346"=>"xp68kg278",
 "numedia:1353"=>"zg64tk99d",
 "numedia:1358"=>"5138jd87r",
 "numedia:1361"=>"x346d4211",
 "numedia:1366"=>"2801pg36g",
 "numedia:1375"=>"zp38wc66m",
 "numedia:1380"=>"wp988j884",
 "numedia:1383"=>"5q47rn72z",
 "numedia:1386"=>"h702q643x",
 "numedia:1390"=>"c247ds185",
 "numedia:1392"=>"zg64tm017",
 "numedia:1395"=>"2514nk52m",
 "numedia:1400"=>"tm70mv177",
 "numedia:1403"=>"3t945q81n",
 "numedia:1407"=>"1r66j1174",
 "numedia:1410"=>"fn106z027",
 "numedia:1414"=>"70795769f",
 "numedia:1418"=>"sq87bt673",

**Comment by egilchrist** [comment]
Hi Jen, 
I looked at j6731382c and 2227mp670.  In the Resource Description "Note" Field it looks like this: 
![screen shot 2017-06-13 at 8 54 35 am](https://user-images.githubusercontent.com/20909880/27085931-4e0391a0-5016-11e7-9418-9e0ba78178bc.png)

Is this correct?  Is this what you want me to make the rest of them look like?

**Comment by jenyoung** [comment]
Yes please.

**Comment by egilchrist** [comment]
All done.
