### ISSUE TITLE
Review media item for deletion

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#132]
Review the following in Avalon. We might be able to delete. 

"numedia:11445"=>"vq27zn474" -- this has audio files but it looks really odd. I can't see the object in AVR 4 so I can't compare. Course Audio / Music Library

**Comment by davidschober** [comment]
whew this is an odd one. @jenyoung @Nic4Images do you have any ideas? I'm going with delete it and move on with life?

**Comment by jenyoung** [comment]
@davidschober @Nic4Images since no one could even see it in old avalon, deleting sounds good to me

**Comment by davidschober** [comment]
@carrickr can you make this so? delete "numedia:11445"=>"vq27zn474" -- this has audio files but it looks really odd. I can't see the object in AVR 4 so I can't compare. Course Audio / Music Library

**Comment by davidschober** [comment]
@carrickr ^^^^
