### ISSUE TITLE
Review two course reserve videos / Audio 

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#133]
deleted all but two from AVR 6 and AVR 4. These objects did not have metadata attached. This was broken out from #124 

Two left from AVR 6 --I hesitated since they are Course Audio objects with metadata.

http://media.northwestern.edu/media_objects/t148fh13t - AVR 4 object -https://legacy.media.library.northwestern.edu/media_objects/numedia:10247
![image](https://user-images.githubusercontent.com/2250501/27059593-f0bdad06-4f9c-11e7-8004-a4c7f7d5d781.png)

http://media.northwestern.edu/media_objects/v405s938k - duplicate record of http://media.northwestern.edu/media_objects/mg74qm15t 
![image](https://user-images.githubusercontent.com/2250501/27059614-15df454a-4f9d-11e7-9a1c-0efd868ed34a.png)

**Comment by davidschober** [comment]
@carrickr is there any more action to be taken here?

**Comment by davidschober** [comment]
@carrickr let me know if we have to do anything else here.

**Comment by davidschober** [comment]
@carrickr ^^^ is this ready to be closed.

**Comment by carrickr** [comment]
It seems like both have been deleted somewhere along the line, so this can closed.
