### ISSUE TITLE
pointer not moving in safari/ multi-sectioned item

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#134]
## Description

when navigating a multi-section item in safari, the track point is not moving. 

## To recreate

Go to:

http://media.northwestern.edu/media_objects/jd472w50p

Press play

Click on another track

note that the player updates, but the track point (on the left) does not move.

**Comment by adamjarling** [comment]
@davidschober I can't access that link.  Which video/audio file is it?  Is there a name or title I could search for?

**Comment by davidschober** [comment]
Sorry. 

Let me make sure you're an admin..Yup, OK try now, exit your browser and all that. Note, this may be a lower priority. It looks like safari moves it when you press "play"

**Comment by adamjarling** [comment]
@davidschober There's definitely some buggy behavior in here, but this will take some time to investigate how the click event delegation is wired up, which files are controlling the click events in the rails app, and so forth.  I'd say we keep this one around when I can have a full day on it.

I did notice some style issues from this view, which I have updated and will push forward.

**Comment by davidschober** [comment]
K. Let’s maybe check to see if this is happening in Avalon core. 

We can look into this later

**Comment by davidschober** [comment]
This seems fixed with 6.3
