### ISSUE TITLE
section label edit box too small

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#135]
## Description

The section label box is too small to be useful for real world editing. This might take some thought, but we need to make label big enough to be readable. 

To recreate:

GO to http://media.northwestern.edu/media_objects/j6731382c/edit?step=file-upload

Click on manage files

note that the section label input field is very small

![screen shot 2017-06-13 at 2 56 26 pm](https://user-images.githubusercontent.com/4803230/27101829-d440802a-5048-11e7-98e9-968f12d6d578.png)

**Comment by adamjarling** [comment]
Yea, this one is tricky.  The only real way to fix this is to change the markup to a flowing form, and get rid of the table structure.  I'll give it a shot w/o destroying functionality, ha.

**Comment by davidschober** [comment]
maybe a back port to core if it works...

**Comment by davidschober** [comment]
@adamjarling and I worked with Molly, she seems happy.

**Comment by adamjarling** [comment]
@davidschober Here's how the pushed version will look.  It plays well responsively as well.

![nu-avalon-associated-files.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f242b74eff97204733762d49a5227c80f06af3006b1300051bff054a5556f9fe8d7ef0b56a708f595eead5395d26c63944acbb8a1cb913a632c91edbe2e3d7158abd7f37ed998c4d341f01118efb5b35a69f48c15df259ac.png)

**Comment by davidschober** [comment]
This looks awesome.

**Comment by davidschober** [comment]
I think we should consider this upstream.

**Comment by adamjarling** [comment]
@davidschober Cool.  Feel free to suggest it to Jon or whoever, and upstreaming would be a good opportunity for me to walk through the process.  We should make sure it is 110% QA'd on our end before suggesting though, right?  Ensure the functionality didn't get lost (I checked, and seemed to work as expected on my end, but maybe there's another way of using it I'm not familiar with).
