### ISSUE TITLE
move ingested files to new s3 bucket

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#136]
## Description

Currently after ingestion of master files, the files stay in the dropbox s3 bucket. We either need to remove them (assuming the master file is moved) or move them to a safe place. 

## Done looks like

After I ingest a file via batch or attaching via dropbox, the source file is moved away so that end users don't see it.

**Comment by mbklein** [comment]
This is finished and deployed, but I'm waiting until Saturday 24 Jun to flip the switch on it.

**Comment by davidschober** [comment]
@mbklein I just noticed this... Did you flip ye olde switch?

**Comment by davidschober** [comment]
@mbklein I'm going to close. Please reopen if need be.
