### ISSUE TITLE
Alternative Audio UI Display?

### ISSUE THREAD

**Issue by adamjarling** [nulib/avalon#139]
### Description
Audio files in NU Avalon have a large amount of blank space underneath the player.  An alternative display could have the audio player be a row, extending 100%, and the metadata could move to it's own row below the player?

Thoughts?

**Comment by davidschober** [comment]
I'm OK with this. @mbklein @carrickr ? Will it take a considerable amount of work? My only concern is that it's moving data around differently for audio/video. Maybe on this one we punt and hold the idea for donut?

**Comment by adamjarling** [comment]
Yea, no problem.  Could be a nice UI upgrade at the appropriate time.
