### ISSUE TITLE
Generate report for DCM to analyze for the 1800+ audio files

### ISSUE THREAD

**Issue by ccaizzi** [nulib/avalon#14]
Michael found 1800+ audio files that did not get moved to farchive during his audit.  He will generate a report with file name and collection for DCM team to determine if there are records in AVR (spot checking makes sense) or if they were part of a failed batch and re-ingested, or if they were test/old files and not supposed to be moved.  related to issue #12 now closed

**Comment by jenyoung** [comment]
Michael created a spreadsheet for DCM to go through. 
[leftover_dropbox_media_files.xlsx](https://github.com/nulib/avalon/files/891292/leftover_dropbox_media_files.xlsx)

Having said that, an initial pass shows that the majority of files are from Course Reserves and MMLC. We will need to confer with them about these files as well.

**Comment by jenyoung** [comment]
Parsed out version of the file. 
[leftover_dropbox_media_files.xlsx](https://github.com/nulib/avalon/files/921012/leftover_dropbox_media_files.xlsx)

**Comment by jenyoung** [comment]
I reviewed what I could of the NUL portion. There's a few that I am unsure about. @Nic4Images can you investigate those please?  Also, @laura-alagna, the Herskovits files that are left seems to have conversion errors. I'm not sure if you're aware. 

I didn't look at the course reserves/mmlc tabs. They should review that part. 

[leftover_dropbox_media_files.xlsx]
(https://github.com/nulib/avalon/files/972136/leftover_dropbox_media_files.xlsx)

**Comment by Nic4Images** [comment]
Shall I ask Cecile and Molly to review the reserves/mmlc tabs or has someone already done that?

**Comment by Nic4Images** [comment]
@jenyoung I reviewed the NUL portion and everything that is left unmarked appears to be @laura-alagna so I have nothing more to add. In the meantime I sent the spreadsheet to Molly and Cecile and asked them to tag their content move or delete.

**Comment by ccaizzi** [comment]
any updates  @laura-alagna and @Nic4Images  from Molly and Cecile.
We need this done before the upgrade ( @davidschober )

**Comment by laura-alagna** [comment]
according to @davidschober the Herskovits files would be a good test case for after the upgrade. Waiting for the green light post-upgrade and I will reingest them then

**Comment by davidschober** [comment]
@laura-alagna go for it. I'm going to close this issue.
