### ISSUE TITLE
Stream AWS Logs to a better location

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#146]
So that Avalon, Fedora, etc logs can be picked up via the AWS Console and viewed from a central location

**Comment by mbklein** [comment]
Worth a look: https://aws.amazon.com/blogs/aws/cloudwatch-log-service/

We can also define custom CloudWatch monitoring metrics and alarms based on log entries.

**Comment by davidschober** [comment]
@carrickr and @mbklein was this completed... I thought I saw MBK do an accidental demo of it in Molly's office.

**Comment by mbklein** [comment]
Avalon's rails and HTTP logs are now streaming to CloudWatch. Fedora and Solr aren't.
