### ISSUE TITLE
Can't reindex_all using Active Fedora on AWS

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#147]
This is a problem, kind of a critical one next time we rebuild.  Issue seems to be the fedora instance runs out of RAM.  

Possible Solutions:
- [ ] bigger instance for Fedora
- [ ] triple store

**Comment by davidschober** [comment]
@carrickr is this unique to AWS? Should we rope Phoung into this?

**Comment by davidschober** [comment]
@carrickr it looks like this is a waiting for staging issue, correct? Like we'll want to see if we can crank up a "worker" fedora to handle a full reindex?

**Comment by mbklein** [comment]
Handling this issue upstream in core.
