### ISSUE TITLE
SOLR backup job to run on avalon

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#148]
Make this an active job that runs regularly

Create a SOLR backup job that runs on an avalon worker

Similar to::: 

```
curl http://solr.repo.vpc.rdc.library.northwestern.edu/solr/admin/collections?action=BACKUP&name=avalon_backup_$(date +%Y%m%d%H%M%S)&collection=avalon&location=/data/backup
```

**Comment by davidschober** [comment]
Currently @mbklein and @carrickr are running daily backup scripts from their desktops. It's not ideal, but we will grab finish this work early next week.

**Comment by mbklein** [comment]
The job is written; we just need to decide how often it should run and schedule it

**Comment by ccaizzi** [comment]
Thanks, @mbklein

**Comment by ccaizzi** [comment]
@mbklein sstill working.  did not run this AM when supposed to.
