### ISSUE TITLE
Create SOLR Restore job

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#149]
make this an active job that can be run via logging into avalon-workers and firing this job off as a perform now

So That:

If solr goes down we can bring it up cleanly from backup. This will depend on 

#148

**Comment by mbklein** [comment]
This doesn't really need to be a job. Since running a one-off job would require `rails console` access anyway, this can be achieved much more efficiently with `SolrCollectionAdmin.new.restore('/data/backup')`.

**Comment by mbklein** [comment]
Abandoning as unnecessary and redundant
