### ISSUE TITLE
Decide on migration path for avalon 4-6 (data + metadata

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#15]
@carrickr can you add a link or drop in the thoughts you wrote up directly here?

**Comment by carrickr** [comment]
@davidschober [White Paper is here](https://northwestern.box.com/s/z3oh0y251x2wbpeu4h4ryw2vwjwc4ghi)

**Comment by davidschober** [comment]
@csyversen and @carrickr I'll have you two help @mbklein out with this. The go live date is critical.

**Comment by mbklein** [comment]
I believe we should identify a subset of items for a targeted test migration. Maybe 25-30 items covering 2-3 collections.

**Comment by davidschober** [comment]
@mbklein done. I just kicked off #41

**Comment by mbklein** [comment]
It is my hope that Avalon itself will be stable enough to start doing iterative test migrations within a few days, whether using the generic or NU skin.

**Comment by davidschober** [comment]
Right, I think we can test migrations without the skin. In fact having data will help Adam in his quest...

**Comment by carrickr** [comment]
@mbklein Do we want to try some course reserve items?  They have full movies in there which seems to the biggest and also comes with a boatload of permissions regarding classes.

**Comment by davidschober** [comment]
@carrickr it looks like we have a plan. Can you write up an extra technical issues and through them in the current sprint?
