### ISSUE TITLE
Discuss AWS is Down Recovery Options

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#151]
For example do we start replicating our S3 buckets (this costs more money)?  
Then we can just form a new cloud in a region other than East (we'd be down while the cloud forms)
Or do we replicate across multiple regions so we have no outage if a region goes down (costs more)

Discuss options and write docs on how to fail over to another region/etc if AWS takes a header

**Comment by davidschober** [comment]
I think we will have to do a cost/benefit analysis. The 2017 one was one off a handful of s3 issues. It was < 5 hours in one region.

**Comment by davidschober** [comment]
Carrick, I think this would be cost prohibitive. I'm going to close this issue at this time. If there's a massive AWS outage, we will have to treat it like a massive NU outage. Assess/ notify/ etc

fyi @ccaizzi
