### ISSUE TITLE
Title not readable when attaching from S3

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#155]
The file is not readable when attaching from s3. Styling should allow for "file" to be very readable for long filenames as admins pack metadata into the filename.

BEFORE:

![image001](https://user-images.githubusercontent.com/4803230/27253030-1a72700e-5331-11e7-928e-22645d61c030.png)

AFTER (this is the new skinned version):
(removed)

**Comment by adamjarling** [comment]
I don't think the 2nd photo (AFTER) is the issue described by Alex.  Seems this is the problem (attached).

![nu-avalon-import-from-s3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f24aa94dff863d0b21612609ee3823c7af6aaf50740b0a0c0abe4b4a5a43f8acdf28f0b63975df5b0fb9d33f5f70933d12a4bb840da313f871d51bdaebe5c01982fa3737e489854e3a17021189fc593da8984dcb4abb.png)

**Comment by davidschober** [comment]
You're right. Grabbed the wrong screen.

**Comment by adamjarling** [comment]
Here's an issue which may require a deeper dive...for some reason there are explicit widths set on column elements in this table.  Either a plugin or a cruel developer's doing, so we'll have to crawl back and find where this is being applied.  

A short term, possible solution (...hopefully) is I can increase the width of the modal window itself, which may give enough room to the column?   Will have to see how this renders for the user, and if still an issue then we can find where the width hardcode is being set.

![nu-avalon-tree-table-modal-column.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f257b658f5d93d47257f2c49ae247484ef65bc4d771402015cb053181d1ba6acda6fb4bc2e758d585ebbd23b5f71c36816a8ec804dbf05ef20884786b0ae965e82b96371b8d6d6056b5c17129bfd5b3fa19d42cf51f64ee84a56a2113571ab.png)

**Comment by ccaizzi** [comment]
We need to have course reserves look at this and sign off.

**Comment by davidschober** [comment]
@adamjarling was this merged?

**Comment by adamjarling** [comment]
@davidschober Yes, that change should be live, but not sure if end users have signed off on it being an acceptable solution or not.

**Comment by davidschober** [comment]
K. I’ll ask Molly.

**Comment by davidschober** [comment]
Hi David,

Thank you!  Yes, this is working.  Much appreciated (:

Molly
