### ISSUE TITLE
Identify MVP Needs for NetGen

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#16]
So my thoughts are we need three main components:  Player, ActiveEncode (for derivatives), and ActiveStreaming.  We'd also have enriched metadata as a need, but it's not minimum out the door.  We can add that in as we go given our current Avalon instance doesn't have particularly rich metadata. 

This would look something like:

**ActiveEncode**
- Ties into HydraDerivatives (integrated into Hyrax)
- Can use ffmpeg (for developer machines)
- Can use Amazon Encode (for production)
- Derivatives are not stored in Fedora / can be accessed with zero Fedora calls

**Player**
- HTML 5 and HLS with fallback option
- IIIF-AV compliant 
- Captions support, but entirely 508c compliant yet
- Integrated into Hyrax, probably in the form of being a Flipflop feature (off is use Hyrax's current lightweight player)

**ActiveStreaming**
- Cloudfront capable for production
- nginx for developers
- Anyone who says use Red5 gets shot with a nerf dart
- Integrated into Hyrax, probably as a Flipflop feature again (off defaults to just play from disk)
- Can stream with zero calls to Fedora for authorization, etc.

Anything else NU needs?  We can probably then evolve these into larger tickets on the main Avalon board.  On our end I'm seeing a workflow of:

- Create the gem / service / whatever
- Get it in Hyrax using Flipflop
- Get a point release of Hyrax cut
- Pull said point release in for our NextGen work
- iterate if it turns out we missed something NU leads for the MVP

**Comment by davidschober** [comment]
Carrick, I'm going to close this and add it to a wiki in the next gen repository.
