### ISSUE TITLE
Grant Carrick Access To the Wowza Server(s) Please

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#17]
Hi,
Can I have access to `libwowza1p.library.northwestern.edu`?  I'd also like to know what you actually it when you SSH into it as I can't even get a response from it when on the SSL VPN.  I don't need any special power perks but I do need to be able to cat logs, etc.

Thanks!

**Comment by Toputnal** [comment]
Hi @carrickr I've setup the requisite accounts for you, so this should be working now.

**Comment by carrickr** [comment]
I'm getting timeouts when trying to connect to `libwowza1p.library.northwestern.edu` via the NU SSL VPN.

**Comment by Toputnal** [comment]
Hi @carrickr.  I have been able to duplicate the problem.  In regard to the SSLVPN subnets, there appear to be some firewall rules missing on the hardware firewall behind which libwowza1p resides.  I will open a ticket with NUIT to add the requisite rules.  The server IS up and accessible from the internal NU network, in case that is useful to know for a temporary workaround while we wait for NUIT.  (ie.  it may be possible to ssh into one box and from that one ssh to libwowza1p).

**Comment by Toputnal** [comment]
Opened support request #523542 with NUIT for this.

**Comment by Toputnal** [comment]
@d-venckus found that NUIT has, in lieu of learning firewalld or using iptables, has configured new RHEL 7 boxes using the good, old, trusty, even-if-limited tcp_wrappers for security on NUIT-managed systems and has included both SSLVPN networks into the allowed list, so @carrickr, you  should be good to go.

**Comment by MarekBabala** [comment]
@carrickr can you test again , Please.  Thanks
