### ISSUE TITLE
Upload from s3 UI enhancements

### ISSUE THREAD

**Issue by adamjarling** [nulib/avalon#173]
### Description
Make some further adjustments to the Add files from S3/Dropbox modal.

### Done Looks Like
- Center checkbox in "Select All" column.
- Remove the 'danger' style from the Cancel button.

![nu-avalon-s3-import-enhancements.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f250f710f999394935676401ad23718be02db24775151c4d52be011a001ea9aacd39aca439778e095dee876d5a71933a15f8bad01fbb54ba23834c83a4a0980e91b6697abad2c51a7c0c0f0a8bf95734a4904cc151f642e34453a01a242e.png)

**Comment by adamjarling** [comment]
@davidschober  Yea, once we move through the functionality, we could move on this.  NU Avalon or Avalon core?

**Comment by davidschober** [comment]
@adamjarling this looks very stale. Closing.
