### ISSUE TITLE
Alternative title layout for Media object preview?

### ISSUE THREAD

**Issue by adamjarling** [nulib/avalon#175]
### Description
Just as a change of perspective, what if the title of a video/audio file was reflected in the page content more typically of a web application, instead of pinned to the right-column 'metadata' area?   Yea/nea?

#### NEW ####
![nu-avalon-media-preview-alt-layout.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f24ea159f995645635763f0da63c3d84ef3cf24e7a18001a0abe5d4a1f06a3a3dc78e2a436628f5b0fb8876e0974c33844abbcd61ded01be758b4c8db5ba9850d2aa6c7bb3d4d216744b470a83ed5f33aa984fc15fff42e04e56a1153e6bf43b.png)

#### EXISTING ####
![nu-avalon-media-preview-layout.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f24ea159f995645635763f0da63c3d89e231b0576f43434d0eee1e020a17b8eb8339a3b13825dc5f5dedd4680a73c26913feb8864abf02b2238d5d99a4fedb1294b7607caddecd5d340c071e83fe593ca79042c95cf54de0485db65e.png)

**Comment by davidschober** [comment]
Yes, let's do this.

**Comment by davidschober** [comment]
@adamjarling I'm closing this one as stale
