### ISSUE TITLE
Playlists sidebar with main content

### ISSUE THREAD

**Issue by adamjarling** [nulib/avalon#176]
### Description
When a playlist has video (maybe audio too?) content in it's left-column, the right-column playlist information layout could be cleaned up.

### Done Looks Like
- [ ] Fix 'Edit Playlist' markup (upstream)
-  [ ] Remove left-padding from unordered list of (? section items)
- [ ] Fix media type icon & total time to look like it flows with the information and doesn't stick out at the end.
- [x] Update selected arrow color to NU purple.
- [x] Have Autoplay toggle left-align, and 'Edit Playlist' button right-align in column, or add more separating space between the two elements.

![nu-avalon-playlist-sidebar-cleanup.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f253a85ce9982055333e3a0da72e7284f165bc4e7e00011a0ebe5d4a1f06a3a3dc78e2a436628f5b0fb8876e0974c33844abbcd61ded01be758b4c8db5ba9850d2aa6c7bb3d4d216744b470a83ed5f33aa984fc15fff42e34e57a0133263f43b.png)

**Comment by davidschober** [comment]
closing as stale
