### ISSUE TITLE
Install AWS Command Line Utility on Avalonweb1p

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#179]
## Overview

MBK and I are finding that some of our derivatives aren't transcoding in such a manner that Amazon can stream them.  So sometimes we need to upload master files to AWS and right now the mount point we can get them from is Avalonweb1p.  So having the AWS utilities would be useful.

## Alternate

I understand we have a file server called Lala.  If that has the master files mounted on them, we could upload from there.  MBK and I would just need access to that server.

**Comment by Toputnal** [comment]
I will add the awscli packages to avalonweb1p which is doing diddly-squat at the moment.

**Comment by Toputnal** [comment]
Done.  @carrickr

**Comment by ccaizzi** [comment]
@carrickr please close if this is what you needed.

**Comment by ccaizzi** [comment]
@mbklein will look into 1p or 2p

**Comment by mbklein** [comment]
@Toputnal @carrickr Whoops; it's avalonweb*2*p that has access to the correct `farchive`mounts. It's got to be easier to install `awscli` on 2p than mount `/farchive` on 1p, right?

**Comment by Toputnal** [comment]
Request the NFS share in question be shared to awalonweb1p :-)  @toputnal

**Comment by Toputnal** [comment]
Opened NUIT Ticket #554353 for this.

**Comment by Toputnal** [comment]
I have farchive19 mounted on avalonweb1p at /farchive19 and farchive20 mounted on avalonweb1p at /farchive20 @mbklein @carrickr @davidschober

**Comment by carrickr** [comment]
Looks good to me!
