### ISSUE TITLE
Metadata problem preventing me from linking item to a class

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#18]
Hi Nicole,
 
I need to add Sharaku <https://avalonweb2p.library.northwestern.edu/media_objects/numedia:47291> to Avalon for a class, and I’m getting the below errors when I Import the metadata (ALMA # 21678441120002441).  Could this be fixed as soon as possible?  I can’t seem to add Access Control for the class until these Resourse Description errors disappear.  Please let me know.
 
Thanks!
 
Molly

![image001](https://cloud.githubusercontent.com/assets/4803230/25506024/2386dbb0-2b6a-11e7-83b9-b95ded5b86cf.png)

**Comment by jenyoung** [comment]
Hi – Molly is using the holding record ID. She should be using the ALMA bib ID. For this item it is 9980502858302441. I think this is the issue.

**Comment by Nic4Images** [comment]
Fixed. Thanks MBK!
