### ISSUE TITLE
Loading Icon on Player

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#180]
Right now when you go to AWS Avalon in Chrome and try to stream something there is a 10 to 15 second delay for the RTMP stream to load.  This is something going on in media element.  @mbklein  profiled the actual load via wireshark and the actual file is taking a tenth of a second to buffer in.  However media element doesn't report ready to stream for that delay period.

This is a bit of a problem since users will probably reload the page before the stream reports ready and restart the whole profile.

There is some kind of event firing when the stream is ready (as the duration goes from 0:00 to the actual time, so something is firing and changing that).  How feasible would it be to stick a loading icon or such on the player until that event files as well?  Then replace it with the play button.

**Comment by adamjarling** [comment]
Yea, I can look into the event timing and see if we can hook into it.

**Comment by adamjarling** [comment]
CSS Spinner used:
https://projects.lukehaas.me/css-loaders/
