### ISSUE TITLE
Input button groups enhancement

### ISSUE THREAD

**Issue by adamjarling** [nulib/avalon#181]
### Description
The 'Add' button is not aligned to the text input field.  Fix the markup.

### Done Looks Like
'Add' button appears connected to the text input.

![nu-avalon-button-input-groups.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e681d7229482a580e7f241b149e49b270b2e7d3911b7667797ec3daf51394d4d1f0cf31b0d0c00eef39b2ea1b26926890a0be8d4385870923f43acbcd71fbc09b926995397f4edd4189fb5646fb2c99d452c1c031288fb543da09c4ec95df44ae64c47e9.png)

**Comment by adamjarling** [comment]
Fix, follow this:
https://www.tutorialspoint.com/bootstrap/bootstrap_input_groups.htm

**Comment by adamjarling** [comment]
Upon inspection, this would require a significant amount of view refactoring.  Will push this off for an upstream fix at some point.

**Comment by davidschober** [comment]
closing as stale
