### ISSUE TITLE
Qatar testing

### ISSUE THREAD

**Issue by ccaizzi** [nulib/avalon#184]
@davidschober look at your email.
Let's set up a basic viewing test with the library director out there.  His contact is in Beth's email.

**Comment by davidschober** [comment]
I noted significant traffic to media objects via analytics. I believe this is working for multiple users now.

**Comment by carrickr** [comment]
<img width="1970" alt="screen shot 2017-10-16 at 6 27 24 pm" src="https://user-images.githubusercontent.com/5350060/31738502-e442ad48-b418-11e7-9c05-fa13a4bf192a.png">

**Comment by davidschober** [comment]
note ^^^ is from amazon's console..
