### ISSUE TITLE
Rewrite Handles to ARKS

### ISSUE THREAD

**Issue by ccaizzi** [nulib/avalon#185]
Investigate writing handles to arks.  Either we do it and try and see if the provider can take over maintaining the handles once we decommission our server.

- [ ] Generate ARKs
- [ ] Verify ARKs exist for every object. 
- [ ] redirect HNDLes to ARKs 
- [ ] remove handles if necessary

**Comment by davidschober** [comment]
@mbklein is this done?

**Comment by mbklein** [comment]
We have generated ARKs for everything, but the handles are still there.

**Comment by davidschober** [comment]
OK. I'm going to move this to "in Review". Is there any reason to remove the handles @mbklein...

**Comment by csyversen** [comment]
so @mbklein has to create arks for all the records that already had handles, so i'll create an issue for that and move it to in progress. 

besides that though, there's about 13.5k records in dynamodb that I can pull and create a batch modify script for handle. I just need to know the ARK url that handle should refer to

**Comment by davidschober** [comment]
@mbklein this never got done right? I'm starting to think we might need a chore sprint this summer.

**Comment by davidschober** [comment]
This is a dupe. We've done some of this work and will fix the rest in #447.
