### ISSUE TITLE
Add GA to media.northwestern

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#205]
It looks like the Analytics code is not properly installed on media.northwestern.edu.

Please use: 

UA-797260-33

I'm wondering if we should set up tag manager for more flexibility in the future. Let's just drop the vanilla tracking code on for now.

**Comment by mbklein** [comment]
If Avalon already includes GA support, this is probably just a matter of setting an environment variable.

**Comment by carrickr** [comment]
@mbklein I don't believe we do, I crawled through the code for a GA gem or analytics config point and found nothing.  However there is a gem for doing basic analytics in rails, PR set.

For more advanced analytics like streaming we might want to consider if we want to go with the advanced analytics or just get the stats from AWS directly.

**Comment by davidschober** [comment]
We should use GA. It makes integrated reporting/ etc considerably easier. I think we should move toward tag manager which should make this kind of work easier. It's a bit more setup initially.

**Comment by davidschober** [comment]
Working. Closing.
