### ISSUE TITLE
Develop plan for Cloudwatch/ Monitoring

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#21]
## Description

As we move forward with the Avalon on AWS pilot, we need a plan for monitoring. If systems fail, people will need to be notified and a call tree will need to be set up to bring the system back up. OPSgenie should get notifications. 

Opsgenie integration with AWS Cloudwatch.

https://www.opsgenie.com/docs/integrations/aws-cloudwatch-integration

## Done looks like

- [x] Team feels comfortable with cloud watch
- [x] initial monitoring is setup and documented. 
- [x] monitoring should be analogous to current monitoring
- [x] errors on ops genie should ping MBK as on call for course pilot

## Systems needing monitoring:

- [x] Fedora
- [x] Avalon Web
- [x] Avalon Workers
- [ ] RDS / Do we need to monitor this? 
- [x] SOLR

**Comment by Toputnal** [comment]
I'll dig in to Cloudwatch and integration for OpsGenie.

**Comment by Toputnal** [comment]
It looks like there is a method to setup SNS Topics in Cloudwatch such that Cloudwatch will send alerts to OpsGenie via OpsGenie's API.  In my test environment I don't have anything to monitor, yet, but I will setup something simple and test the Cloudwatch integration.  If all goes well, then we'll need to configure our production Avalon instance's Cloudwatch with SNS alerts to OpsGenie's web API.  @d-venckus @davidschober @mbklein   If we do this, then we can setup OpsGenie to alert whoever, whenever, via OpsGenie's integrated scheduler.

**Comment by Toputnal** [comment]
Oh, and I should mention that if an alert clears itself in CloudWatch, that will automatically update and close the alert in OpsGenie, assuming we get the integration setup as I mentioned above.

**Comment by d-venckus** [comment]
Unlike with Solarwinds, lately, where I’ve been clearing alerts, only to have OpsGenie persist in endless badgering.  Sigh.

--D

________________________________________
David Venckus,    DevOps Systems Administrator
Library IT Infrastructure
Northwestern University Library
d-venckus@northwestern.edu<mailto:d-venckus@northwestern.edu>

**Comment by Toputnal** [comment]
I have created an Topic in our AWS instance so that any messages that go to @mbklein's email also alert OpsGenie, theoretically.  We could use some kind of artificial alert to ensure things are working, but I'll leave what that test might be to @mbklein.  @davidschober

**Comment by davidschober** [comment]
@Toputnal Not sure what you mean with the last comment. I think we need to ensure the main systems are up and respond 

- Fedora
- Avalon Web
- Avalon Workers
- SOLR

Is that what you're looking for?

**Comment by Toputnal** [comment]
Oh, sorry.  When I was poking around in our AWS stuff I saw an alert rule already that was set to email MBK, which I copied to create a rule that has the same triggers as the existing alert rule.  So, whatever MBK was getting emailed about will now also go to OpsGenie.  That’s the theory, anyway.

Creating some test/false-alert/etc. that will cause MBK to receive an email alerts from AWS, should let us know if the CloudWatch/OpsGenie connection is working correctly.

If all is well, then we can write any additional  alert rules for whatever is desired, but, at this point, this is a test of the inter-connect between the monitoring/alerting systems.

Best Regards,

--Jim

--
James R.  Bottino
Senior DevOps SysAdmin
Northwestern University Libraries
Northwestern University
www.library.northwestern.edu
james.bottino@northwestern.edu<mailto:james.bottino@northwestern.edu>
847-491-8389

**Comment by Toputnal** [comment]
@davidschober ^

**Comment by d-venckus** [comment]
Will OpsGenie also alert MBK a second time, Jim?  Is that the idea?  To test OpsGenie connectivity fully?

**Comment by Toputnal** [comment]
Eventually, yes, @d-venckus, but for now I just wanna see some Blinkin' lights!  :-)

**Comment by davidschober** [comment]
Got it. Can someone document what we're monitoring?

**Comment by Toputnal** [comment]
I'm not certain what the existing monitoring that is setup in AWS is actually monitoring.  (That is, what alarms are currently setup to email @mbklein).  I'll dig in and see what I can find (without changing anything, at first, obviously).  If I accidentally break anything, our SOP is to blame  @egspoony ;-) (Back me up on this @d-venckus)!

**Comment by Toputnal** [comment]
I have setup alerts for all the services listed above, minus RDS which is provided as a service to us rather than being a service that we run on top of some EC2 instance.  Does what I've added look good to @d-venckus , @davidschober @mbklein

**Comment by Toputnal** [comment]
I have setup a Dashboard in CloudWatch called "JRBDashboard" which shows what things we are now setup to alert OpsGenie, so that's probably a good place to look at our current AWS/OpsGenie integration.  @d-venckus @mbklein @davidschober

**Comment by davidschober** [comment]
@mbklein I'll let you take a peak and OK it. @Toputnal and @d-venckus can you write up some brief docs on what we are monitoring, how to set it up, etc? You can put it <https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-Technical-Documentation#monitoring-via-cloudwatch> or you can send me a doc and I can c&p.

**Comment by Toputnal** [comment]
I will update the doc you listed above @davidschober as soon as we stabilize the thresholds of the things we are monitoring.  Currently, we have quite a bit of "noise" which we are still ironing out.

**Comment by davidschober** [comment]
Thanks @Toputnal

**Comment by Toputnal** [comment]
I need to see if any of the checks I wrote need to be fixed after MBK did the latest burndown/build, and, if so, fix them.  I will close, or move to Review, this once I’ve verified this.  I don’t want us to *think* we’ve got monitoring covered when it *may* be broken.  I’ll look today.

Best Regards,

--Jim

--
James R.  Bottino
Senior DevOps SysAdmin
Northwestern University Libraries
Northwestern University
www.library.northwestern.edu
james.bottino@northwestern.edu<mailto:james.bottino@northwestern.edu>
847-491-8389

**Comment by davidschober** [comment]
Sounds good!

**Comment by Toputnal** [comment]
All the alerts I created are still in place after the burn down, and rebuild.  Yay!  Moving to Review.
