### ISSUE TITLE
Help NU Canvas Team Generic Embed Work in Canvas

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#212]
IU's canvas admins did some configuration that allows Avalon's generic iframe embed to work in canvas.  They did some customization where when a user pasts in an Avalon iframe, canvas automatically inserts a second iframe that runs the LTI auth and allows the iframe to work.  Jon Cameron has some contacts at IU's Canvas Team that might be able to shed some light on how to do this.

**Comment by davidschober** [comment]
Is this a "someday" @carrickr and @mbklein or do we want to push to get this done?

**Comment by davidschober** [comment]
done per API work. Any old link will work!
