### ISSUE TITLE
Batch ingest is successful, but media is not attaching and duplicates are created 

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#216]
## Description 

When kicking off a batch ingest using the attached Spreadsheet, items duplicate, and no media is attached. We attempted to upload twice with different results (699 and 979 total items were created). 

To recreate:

* Remove items from Herskovitz
* Use attached SS and assets
* see that no media is attached to most items

[batch_manifest.xlsx](https://github.com/nulib/avalon/files/1125569/batch_manifest.xlsx)

[herskowitz](http://media.library.northwestern.edu/?f%5Bcollection_ssim%5D%5B%5D=Herskovits+Library+of+African+Studies+Audio+Collection&search_field=all_fields)

Note, when this is fixed notify @jenyoung

**Comment by davidschober** [comment]
ping @laura-alagna

**Comment by davidschober** [comment]
Note, some are being duped. They seem to be coming from the top portion of the sheet http://media.library.northwestern.edu/?q=Bloke+Modisane+interviewed+by+Lewis+Nkosi&search_field=all_fields

**Comment by carrickr** [comment]
For the record on this:

- In the short term users need to use sub 300 item spreadsheets, on Friday Laura had items time out.
- We appear not to be able to do small sheets in parallel.  I tried that with the most recent ingest attempt.  I submitted Sheet1 with 86 items and Sheet2 with 90 items. Upon uploading Sheet2, Sheet1's ingest failed with a modeshape error (see below).  Submitting the two sheets in serial worked fine.
- In the longer run we need to rearchitect how Avalon does batches, I have some thoughts on that
- MBK has some thoughts for fixes to Fedora that also help with this

Error when running in Parallel
```
Manifest file: s3://avalon-masterfiles-cfx3wj9/dropbox/Herskovits_Library_of_African_Studies_Audio_Collection/batch_manifest.xlsx

Ldp::HttpError: STATUS: 500 org.modeshape.jcr.value.binary.BinaryStoreException: org.modeshape.jcr.value.binary.BinaryStoreException: Unable to find binary value with key "7dea9824ca98bb19a19c09e3df03866ebd00ad77" within binary store at "/var/cache/tomcat8/temp/modeshape-binary-store" at org.modeshape.jcr.value.binary.S3BinaryStore.storeValue(S3BinaryStore.java:213) at org.modeshape.jcr.value.binary.AbstractBinaryStore.storeValue(AbstractBinaryStore.java:251) at org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:257) at org.modeshape.jcr.value.binary.BinaryStoreValueFactory.create(BinaryStoreValueFactory.java:49) at org.modeshape.jcr.JcrValueFactory.createBinary(JcrValueFactory.java:149) at org.modeshape.jcr.JcrValueFactory.createBinary(JcrValueFactory.java:41) at org.fcrepo.kernel.modeshape.FedoraBinaryImpl.setContent(FedoraBinaryImpl.java:178) at org.fcrepo.http.api.ContentExposingResource.replaceResourceBinaryWithStream(ContentExposingResource.java:612) at org.f...```

**Comment by mbklein** [comment]
I solicited some input from the AWS community here: https://forums.aws.amazon.com/message.jspa?messageID=793849#793849
