### ISSUE TITLE
Some movies not accessible from Canvas

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#217]
## DESCRIPTION 

Course media is not accessible from within Canvas. Some professors have started to notice that course material is not accessible. To recreate, go to a course that has media, see that media is not accessible.

Note, this is not happening on all courses. @mbklein has started to investigate. 

-----

EMAIL STRING

Is there some work being done? I’m not able to log in and look into this error. We got notices from other faculty as well that they can’t access items for their courses. 

Let me know if something’s going on and when the repository will be accessible. 

Thanks, 

Alex Barontini
 
From: University Library 
Sent: Wednesday, July 05, 2017 8:27 AM
To: Main Library Reserves <e-reserve@northwestern.edu>
Subject: FW: required movie in "Library Media" is not available for viewing
Importance: High
 
FYA
 
Geoff Swindells
---
Geoffrey D. Swindells
Library Ombudsman
Northwestern University Libraries
 
 
 
From: Gordon S Swartz <gordon.swartz@northwestern.edu>
Date: Wednesday, July 5, 2017 at 12:56 AM
To: University Library <library@northwestern.edu>
Subject: required movie in "Library Media" is not available for viewing
 
Dear Librarian:

I am an instructor in the MSPA program. I placed the "Moneyball" movie on reserve at the beginning of the Summer term (see notes from the Canvas platform Library Media page below).

Several of my students have complained that they cannot view the movie.  I tested the movie this evening, and it did not work.  

When I clicked on the title of the movie to begin streaming, as I have in the past, the system gave me the following error message:  
We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

I don't know what the "logs" are or how to check them.  The movie is available for students to stream.

Can you please help asap?  The students have a written, graded assignment due this week, and the assignment is based in part on viewing the movie.

Thank you,

Gordon Swartz

***** notes from Library Media page *****

1. Moneyball (2:14:04)
Selected
Date:
2012 (Creation date: 2011)
Main contributors:
Miller, Bennett
Summary:
NUSearch record: http://search.library.northwestern.edu/NULV:voyager6162864

**Comment by carrickr** [comment]
So I see Moneyball has having four SU courses and after adding in the Avalon Test Course I can play it back via Canvas.

@davidschober I think the next step is to add me into one of the courses Gordon Swartz is teaching so I can attempt to stream while tailing logs.

**Comment by davidschober** [comment]
Fedora was down. @carrickr moneyball ...

**Comment by carrickr** [comment]
Well that makes it easy, close?
