### ISSUE TITLE
Add new image for Herskovits collection

### ISSUE THREAD

**Issue by adamjarling** [nulib/avalon#224]
### Description
Update the homepage image for Herskovits collection

### Done Looks Like
Replace with the attached image

**Comment by adamjarling** [comment]
![inu-mckay-gh-229](https://user-images.githubusercontent.com/3020266/28284542-eb14fa60-6af6-11e7-9edb-9544f88a4fdd.jpg)

**Comment by laura-alagna** [comment]
Hi @adamjarling - any idea when this will go live? I'm still seeing the old image on the homepage. thanks!

**Comment by adamjarling** [comment]
@laura-alagna Let me check.  This was done a while ago...

**Comment by adamjarling** [comment]
@mbklein @carrickr Looks like this fix was pushed to `deploy-aws-staging`.  Any ideas on when it might go live for @laura-alagna ?
