### ISSUE TITLE
Embedded videos are very dark

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#228]
Josh noted that embedded videos are very dark (compared to original).

To recreate:

1. embed video on an html page
2. look at video and compare to original
3. note it looks like there's a dark overlay or something.

![screen shot 2017-07-20 at 4 55 47 pm](https://user-images.githubusercontent.com/4803230/28440541-5905cf0a-6d6c-11e7-94af-bee8e7d065b0.png)
![screen shot 2017-07-20 at 4 55 02 pm](https://user-images.githubusercontent.com/4803230/28440542-590dcf2a-6d6c-11e7-868a-2cd8762d483b.png)

**Comment by davidschober** [comment]
@carrickr and @mbklein can any ideas?

**Comment by adamjarling** [comment]
This has to do with the custom loading spinner we put on videos.  Since the embedded player doesn't have the custom loading spinner javascript, the opacity css never gets brought back up to a full "1".  I'll adjust how we're applying the CSS to fix.

**Comment by adamjarling** [comment]
There were a few issues with the custom loading spinner not showing on embedded usages as well.  I believe I have most fixed, however @mbklein or @carrickr , could you point me in the direction of a live URL where someone is really embedding a video?   I want to make sure it works outside of my local embedding testing.

**Comment by davidschober** [comment]
There's a video here:

http://imaginationwithoutborders.northwestern.edu/about/

Down one the page.

**Comment by adamjarling** [comment]
@davidschober Great, thanks.

**Comment by davidschober** [comment]
@carrickr let me know when you're going to do a reply.

**Comment by davidschober** [comment]
This fix seemed to work. Top live avalon, below staging.


![screen shot 2017-08-02 at 11 22 21 am](https://user-images.githubusercontent.com/4803230/28883699-f563223c-7774-11e7-9a90-5eec9c2092e0.png)


Let's get this merged and deployed @carrickr @mbklein @adamjarling

**Comment by davidschober** [comment]
ignore the last one. I just realized i was looking at the wrong avalon. checking now.

**Comment by adamjarling** [comment]
@davidschober New code fix is not being served yet.

**Comment by davidschober** [comment]
This looks fixed on staging. 
![screen shot 2017-08-03 at 11 18 31 am](https://user-images.githubusercontent.com/4803230/28932097-ebdd8684-783d-11e7-81d8-c2efb0c4fd00.png)

Production left, staging right.

**Comment by davidschober** [comment]
Great work all.
