### ISSUE TITLE
Update Monitoring Documentation

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#233]
## Description

We have changed/ tweaked our monitoring for production Avalon. Cloud watch now kicks off pages to our internal system and updates slack. @Toputnal and @d-venckus can you update the technical docs with how it works/ who's getting notified. [monitoring](https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-Technical-Documentation#monitoring-via-cloudwatch)

Much was changes as part of #161. We should document:
* What endpoints we're monitoring
* What methods we're using to monitor (expected response / errors
* Who/what is being notified 

## Done looks like
- [ ] [docs](https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-Technical-Documentation#monitoring-via-cloudwatch) are updated
- [ ] one person reads and agrees it jives.

**Comment by davidschober** [comment]
@Toputnal @d-venckus low hanging fruit here.

**Comment by davidschober** [comment]
@Toputnal now that we've updated monitoring/ health checks can you update the docs. Ideally we should have links to AWS docs referencing how/ why we're checking stuff. We should grab this for the next cycle.

**Comment by davidschober** [comment]
@Toputnal I think this is in progress. Can you have @d-venckus read it and make sure he can recreate it if need be?

**Comment by davidschober** [comment]
@Toputnal I think this is done right? You're comfortable with the docs?

**Comment by MarekBabala** [comment]
The Group decided we need more info on the Docs page.

**Comment by d-venckus** [comment]
The docs are not sufficient, I'd say, to properly diagnose a complex issue.  We need to walk through both the document and the configuration to identify what's missing.

**Comment by egspoony** [comment]
@d-venckus, @MarekBabala, @Toputnal will meet and discuss and will then generate a specific list of questions for @mbklein

**Comment by MarekBabala** [comment]
Scheduled this for This Friday 2PM

**Comment by MarekBabala** [comment]
Scheduled fro THURSDAY 2PM - 3:30AM

**Comment by egspoony** [comment]
Meeting was had, new meeting will happen where screenshots will be added. This work will be reflected in issue nulib/devops#304
