### ISSUE TITLE
Document SOLR backup

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#234]
## Description

We want to make sure our SOLR cores are backed up regularly so that in an emergency we can bring the system back up from a dated back up. This hole was noted during a review with Devops.

[Original Notes during doc session](https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-AWS-Overview-and-Outage-Protocol#creating-solr-backups)

## Done looks like

- [x] SOLR is backed up with something like: 
```curl http://solr.repo.vpc.rdc.library.northwestern.edu/solr/admin/collections?action=BACKUP&name=avalon_backup_$(date +%Y%m%d%H%M%S)&collection=avalon&location=/data/backup```
- [x] backups are stored on s3 bucket and documented
- [x] SOLR restore is tested (in staging and later on prod with downtime noted)
- [x] procedures for returning from a system failure are documented.

**Comment by davidschober** [comment]
@mbklein and @carrickr did this already get done? If so can we document in the referenced doc and close it out? If it's no longer valid, let's just make sure we doc how to come back from the dead.

**Comment by davidschober** [comment]
Backups are being taken and stored on EFS.

**Comment by egspoony** [comment]
@Toputnal @mbklein Document this and how to restore from backup.

**Comment by MANorth** [comment]
@mbklein MBK, could you meet with @Toputnal Jim and document this soon.  Otherwise it will wait until January and things might get fuzzy.  Thanks.

**Comment by Toputnal** [comment]
I have written up an initial draft here.  https://github.com/nulib/repodev_planning_and_docs/wiki/SOLR-Backup-to-EFS-on-aws

**Comment by Toputnal** [comment]
Created 
#279 Verify that Solr is being backed up in aws
#280 Document how Solr is backed up in AWS
#281 Test documentation in #280

**Comment by Toputnal** [comment]
Update Documentation to include information on how the solr backups are generated.  There must be a script and a cron job or something of the sort.

**Comment by Toputnal** [comment]
@mbklein I am not sure how this solr backup script gets generated.  Is this something that gets untared into / or whatnot?

**Comment by davidschober** [comment]
@Toputnal is this done?

**Comment by Toputnal** [comment]
Yep.

https://github.com/nulib/repodev_planning_and_docs/wiki/SOLR-Backup-to-EFS-on-aws
