### ISSUE TITLE
Standup Avalon from Avalon Cloudformation Script

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#236]
## Description

in order to ensure our team is learning cloud formation @d-venckus and @Toputnal should stand up the Avalon (and the whole eco-system) inside of a  AWS. 

## Notes

Cloud formation script
https://github.com/avalonmediasystem/avalon-aws

**Comment by Toputnal** [comment]
I am working through standing up everything using the cloudformation templates/configs in NUL-IT-Sandbox-Admis.

**Comment by Toputnal** [comment]
I have reached out to Phuong  to see if he can give me any pointers as to where to start.  A directory full of template files just leaves me guessing how things ought to work.  (Not that I let that stop me from trying stuff.  :-)  )

**Comment by Toputnal** [comment]
I have setup a new DNS delegation for devops-test.library.orthwestern.edu which I am using to spin up things in the AWS Sandbox via the CloudFormation script.  Currently, I am debugging errors as I encounter them.

**Comment by davidschober** [comment]
Great Jim! Dig around in there. Make sure you spin down instances. And one thing we realized is creating and destroying a bunch in a row causes extra charges ...

**Comment by Toputnal** [comment]
Really?  Thanks!  I would not have guess that that would be the case. So far I haven't gotten anything to spin all the way up, yet, so the point is Moo, like a cow's opinion; it doesn't matter.

**Comment by Toputnal** [comment]
We have crashed in newer and more exciting places.  @mbklein can you take a peek, please?

**Comment by Toputnal** [comment]
I have been working on this, playing whack-a-mole, as it were, but I understand much better how all these components work together.  I have continued to document any notes, gotchas, etc. here https://github.com/avalonmediasystem/avalon-aws so far I have not hat the infrastructure.yaml stack come all the way up without errors (things like changed filenames or "hard-coded" Amazon Linux images that are no longer available.  I've seen it *nearly* complete a build a couple of times, but won't count this as done until I get both the infrasructure.yaml AND the application.yaml deployed along side.

**Comment by Toputnal** [comment]
I have been making progress on this.   Thank you, @mbklein !  May I introduce to you, the Slee-Stack, the first successful build of the cloudformation scripts.  w00+!  @davidschober   @rtrautve1  @d-venckus 

Now, on to building the second tier...

**Comment by davidschober** [comment]
Awesome! send out a link! @Toputnal

**Comment by davidschober** [comment]
oops, accidentally closed. 

@mbklein should we move the formal docs to a wiki page within the Avalon context when it's done? I know you wanted to merge AWS stuff.

**Comment by Toputnal** [comment]
The how-to, README.md has been moved to a private repository here: The how-to, README.md has been moved to a private repository here:

**Comment by Toputnal** [comment]
Current status: The infrastructure stack (slee) is up and running.  Getting the Avalon application stack to build on top of the infrastructure stack is the current holdup.  I have contacted @mbklein.  Will update here when there is something to report.  :-)

**Comment by Toputnal** [comment]
Howto has been moved to the Wiki here:  https://github.com/nulib/repodev_planning_and_docs/wiki/AWS-CloudFront-Templates

**Comment by Toputnal** [comment]
The Dev instance of Avalon on AWS is up and running under our sandbox account!  We'd like to burn it all  down and bring it up again, soon, but it's up for the nonce.  http://smoke.slee.devops-test.library.northwestern.edu @davidschober @rtrautve1 @d-venckus @ccaizzi
