### ISSUE TITLE
Error uploading video

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#243]
![image001](https://user-images.githubusercontent.com/4803230/30608527-5192b63c-9d3e-11e7-8e18-f1ab5da81690.png)

So, I’m getting this error when I try to add a file to Avalon from the dropbox.  I think I have a (rather time-consuming) workaround, BUT if this could be looked at and quickly fixed that would be super.
Thank you!
Molly

**Comment by carrickr** [comment]
Which specific file in the dropbox?

**Comment by davidschober** [comment]
IT looks like this sorted itself. I went and talked with Molly.
