### ISSUE TITLE
Having trouble ingesting either the metadata or  file 

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#248]
@Nic4Images and John B. were trying to ingest a file that is coming from our Acquisitions workgroup.

Upload via web form: 
* .flac file is the within the parameters of size. successfully upload the file.
* Move on to the metadata form - enter Catalog Key for the ALMA record (9980573967402441). Everything imports correctly except the date is empty. I add the correct date information and I get a big red error message saying "There are errors with your submission. Please correct them before continuing."
* Sidenote: the date is empty because I'm guessing our MARC mapping needs to be updated to account for 264 fields (old usage: 260 field)

Upload via batch:
* create a CSV file using the .WAV file. The .csv file keeps getting a .error and I have no idea why.

All of the files are in the dropbox under Northwestern_University_Libraries

Name of file(s): 
Cherie_Rogers_-_An_Oddly_Complete_Unders.flac (200 MB)
Cherie_Rogers_An_Oddly_Complete_Unders.WAV (481 MB)
jb_test.csv

**Comment by Nic4Images** [comment]
@carrickr @davidschober should I hold off on trying to train John B (again) this afternoon until this is fixed? I am thinking so but want confirmation from you. Thanks, N.

**Comment by jenyoung** [comment]
@Nic4Images this was resolved wasn't it? it was the dates being |||| correct?

**Comment by davidschober** [comment]
closing. I think this was sorted.
