### ISSUE TITLE
Avalon 6.3 Upgrade

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#249]
# Initial Deployment
- [x] Merge core 6.3 into NU's aws staging branch
- [x] Port AWS Configuration to AWS
- [x] Deploy NU 6.3 to AWS Staging

# Batch Ingest
- [x] Complete S3 Batch Ingest 
- [x] Contribute Job Back to Core
- [x] Contribute Documentation on Tuning Back to Core
- [x] Extensively test Batch Ingest

# Fedora Upgrade
- [x] Install a Fedora That Can Handle Multiple Writes
- [x] Test Said Fedora

# Batch and New Fedora
- [x] Attempt more aggressive tuning on the new Fedora

# Streaming
- [x] Shutdown RTMP Streaming
- [x] Extensively test streaming for new player
- [ ] Delete RTMP derivatives from staging as part of RTMP streaming test

# UI
- [x] Review views that were updated in 6.3 and ensure our skinning does not conflict with rewritten views 
- [x] Test playlists extensively for fixes
- [x] Specifically check playlists for skipping of the first item and jumping too far in

**Comment by davidschober** [comment]
@carrickr you noted "update ruby on ec2" is that critical?

cc: @mbklein

**Comment by adamjarling** [comment]
@davidschober or @carrickr  If you want to verify your use case for the 3rd UI point above "Specifically check playlists for skipping of the first item and jumping too far in", feel free to double check and catching anything I'm missing.
