### ISSUE TITLE
CSS Bug When Alerting Users to Required Fields

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#250]
<img width="1685" alt="screen shot 2017-10-02 at 12 00 26 pm" src="https://user-images.githubusercontent.com/5350060/31086960-5c8d715a-a769-11e7-83f7-c842dc8059dd.png">

(Note how I had to highlight Publication Date and the error with my cursor to see the text)

To replicate:

1.  In Avalon create an item
2. Leave at least one required field blank (ex: Publication Date)
3. Hit save, error message fails to display

**Comment by adamjarling** [comment]
@carrickr I'm currently blocked from running or doing anything on NU Avalon locally.  Are you able to build the latest `nu-develop` locally?

**Comment by carrickr** [comment]
@adamjarling I haven't kicked it up locally recently, what kind of error are you getting?

**Comment by adamjarling** [comment]
This is fixed locally, but I can't verify it works on staging (https://avr.repo.rdc-staging.library.northwestern.edu).  I don't have permissions to add / edit on staging.  @davidschober can you verify this fix made to staging?

**Comment by adamjarling** [comment]
@davidschober Mind having a look at this and verify it's fixed?

**Comment by adamjarling** [comment]
Looks good to me.
