### ISSUE TITLE
Verify Instance Relacement for Avalon Webapp Is Working

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#251]
We should now we cycling out the webapp instance every night at midnight (to ensure a fresh Avalon and avoid Puma leakiness).  Verify that every AM we have an instance that scaled up at midnight Central / 6 am UTC.

**Comment by carrickr** [comment]
Apparently you need to put quotes around your chron notation like:

`"0 6 * * *"`

So the swap failed to run last night before I just used:

`0 6 * * *`

Fixed this and will check it again tomorrow.

**Comment by carrickr** [comment]
This worked, although due to auto deploying bad code it actually took the entire server now, see #254.

@davidschober @mbklein: We may want to discuss the implications of auto deploying every night and having dependencies break on us vs doing it manually.

If we do keep this auto I vote we move to a set time during working hours.  The way this works is:

1.  We set `Desired Instances` (which is a temporary flag) to 2, causing a new instance to spawn if the webapp is currently at 1.
1.  After 15 or so minutes the load balancer notices that we have 2 instances up but our `Minimum Instances` is set to 1 and we don't have the the load to justify having two instances.
1.  The old instance, aka the one more likely to have a leaky Puma/etc, is shut down.

So to the end user there is no disruption since we add an instance before subtracting.  If Avalon is already under load and has 3+ webapp instances up, this is basically a no-op.  We can assume if we have three instances up, we have at least some fresh instances up and the freshest is kept when the load ends and we scale down.

The negative potential is obviously a repeat of #254, but if we do it during working hours there will be devs in to fix it, as opposed to being down for 7+ hours before anyone arrives at work and notices.

My other thought is to less aggressive refreshing and do it at say 6 am every Monday, since we have workers manually test instances first thing Monday morning.  See if a once a week refresh is good enough.

**Comment by davidschober** [comment]
I'm comfortable with auto deploying during work hours. @mbklein do you want to weigh in?
