### ISSUE TITLE
Postmortem on 4 Oct 2017 Outage

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#254]
`media.northwestern.edu` went down at 1 am Central when a new webapp container deployed, as part of the changes being made in #251.  Avalon has been set to spawn a fresh container every night to refresh the system since we were seeing Puma cause slowdowns over time.

However the Ruby app failed to deploy due to the git history of `mediainfo` being changed as part of work for the release of Avalon 6.3 in the public branch.  As shown in `eb-activity.log`:

```
  + bundle install
  Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
  installing your bundle as root will break this application for all non-root
  users on this machine.
  Warning: the running version of Bundler (1.15.0) is older than the version that created the lockfile (1.15.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
  Fetching gem metadata from https://rubygems.org/.......
  Fetching version metadata from https://rubygems.org/..
  Fetching dependency metadata from https://rubygems.org/.
  Fetching https://github.com/avalonmediasystem/avalon-workflow.git
  Fetching http://github.com/projecthydra-labs/active-encode.git
  Fetching https://github.com/avalonmediasystem/mediainfo.git
  fatal: Could not parse object 'f6d7a14c5035effc9eb9986ff56621b020ebc27f'.
```

The fix was to update the `Gemfile.lock` and redeploy the code, point to a known good `mediainfo`

So we had two points of failure.

1.  AWS somehow decided even though `bundle install` failed on this new container, that all health checks had passed and swapped the new container in.
1.  We appear to have no monitoring/alerts since for ~7 hours every request to Avalon would have resulted in a 500 due to there being no running Ruby webapp.  I only noticed because I was checking to make sure the #251 chron task ran and happened to pull up the webapp.  Had I not, we would not have found out until a user noticed.

There is also a developers practice issue about pegging the `Gemfile.lock` to a specific commit that can be squashed or otherwise impacted by a git history rewrite rather than something more permanent.

**Comment by ccaizzi** [comment]
Course Reserves noted Spanish 201, Spanish 121, and a 3rd course were impacted.

Andrew Dice from Canvas support intercepted other complaints.   A system wide message to CANDUITS was sent at 10:30am and a resolved one was sent at 11am.
