### ISSUE TITLE
Expose the Is It Working Page

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#255]
Expose the `is_it_working`, aka status page, so devops can monitor it.  Right now it is disabled and won't display.

Pass the URL to dev-ops when this is deployed.

**Comment by davidschober** [comment]
Note, this should be monitored as part of a health check.

**Comment by davidschober** [comment]
Note, it looks like we can use basic health-checks in conjunction with a page like this. We can point the health check at an arbitrary URL.  If we have a page return either 200 or 500 (any error), the health-check url can be tweaked. 

CITATION http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.healthstatus.html

> You can choose to override this setting by specifying an existing resource in your application. If you specify a path, such as /health, the health check URL is set to http:80/health. The health check URL should be set to a path that is always served by your application. If it is set to a static page that is served or cached by the web server in front of your application, health checks will not reveal issues with the application server or web container. For instructions on modifying your health check URL, see Health Check.

> If a health check URL is configured, Elastic Load Balancing expects a GET request that it sends to return a response of 200 OK. The application fails the health check if it fails to respond within 5 seconds or if it responds with any other HTTP status code. After 5 consecutive health check failures, Elastic Load Balancing takes the instance out of service.

**Comment by davidschober** [comment]
Also note this note

> Configuring a health check URL does not change the health check behavior of an environment's Auto Scaling group. An unhealthy instance is removed from the load balancer, but is not automatically replaced by Auto Scaling unless you configure Auto Scaling to use the Elastic Load Balancing health check as a basis for replacing instances. To configure Auto Scaling to replace instances that fail an Elastic Load Balancing health check, see Auto Scaling Health Check Setting.

**Comment by davidschober** [comment]
@carrickr @mbklein  can we have the avalon health page return a non-200 code if any core service is not green? That way the alarm goes off (or the instance fails to deploy) if the health check is anything but 200? ) This would be similar to solr 's admin/core/status.

**Comment by davidschober** [comment]
closing as very stale.
