### ISSUE TITLE
Look into Log Streaming for Multiple EC2 Instances

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#262]
Right now logs are available only in the form of being downloaded from one instance, so to troubleshoot a problem when there are multiple instances up or a previous instance has the relevant error, it requires downloading and combining multiple archives by hand.  Look into log streaming for all instances of the same time (Zookeeper, Solr, Rails App)

See here for some info on log file config:
http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html

**Comment by carrickr** [comment]
Webapp done here:

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:prefix=/aws/elasticbeanstalk/avalon-webapp/

should do the others though

**Comment by davidschober** [comment]
We have documented how to read log files. https://github.com/nulib/next-generation-repository/wiki/accessing-rails-logs-via-cloudwatch-(ALL-ENVS)
