### ISSUE TITLE
Comments not going to proper email list

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#264]
## Description

The comment field was not sending emails. It appears that the configuration was wrong.

Please update to repository@northwestern.edu

@carrickr cc

**Comment by davidschober** [comment]
@Nic4Images @egilchrist can you test the comment form now? It should be working.

**Comment by egilchrist** [comment]
Hi.  I clicked on the "Help" button in Avalon and submitted a comment.  The system says "We have received your comments and will respond as soon as possible." 

Nothing has come into the Repository email though.

**Comment by carrickr** [comment]
Redeployed with `repository@northwestern.edu` and ready to retest.

**Comment by egilchrist** [comment]
Hi. I just sent another help/comment on Avalon and nothing came through to repository@northwestern.edu

**Comment by carrickr** [comment]
@egilchrist Sorry, mbk just noticed we have workers with the old config still floating around, I'm replacing them

**Comment by egilchrist** [comment]
Hi. The repository email just received an Avalon feedback notice from MBK "Just testing mail sending from the console"

**Comment by carrickr** [comment]
@egilchrist Workers environment updated, I sent an email through the webapp at 4:23

**Comment by egilchrist** [comment]
@carrickr Nothing has come through yet.

**Comment by egilchrist** [comment]
I just sent one through the website at 4:37.

**Comment by carrickr** [comment]
`repository@northwestern.edu` was never verified, sent a verification from AWS to that email and had it verified

SES is showing three emails sent today, but not incrementing as I test more via the website (should be at 5 right now)

**Comment by egilchrist** [comment]
Hello.  "Test from AWS SES Console" just arrived in repository email

**Comment by carrickr** [comment]
```
I, [2017-10-17T22:01:38.463573 #26106]  INFO -- : method=GET path=/ format=*/* controller=CatalogController action=index status=200 duration=204.41 view=133.33 db=0.73 time=2017-10-17 22:01:38 +0000
I, [2017-10-17T22:01:38.589445 #26106]  INFO -- : [Aws::SQS::Client 200 0.050292 0 retries] send_message(queue_url:"https://sqs.us-east-1.amazonaws.com/845225713889/avalon-DefaultQueue-17IG5WZQ3D9G4",message_body:"{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"327e07d9-3d6f-4293-b3bb-9b94bec87b4f\",\"queue_name\":\"mailers\",\"arguments\":[\"CommentsMailer\",\"contact_email\",\"deliver_now\",{\"name\":\"Carrick Rogers\",\"subject\":\"Technical support\",\"email\":\"carrick.rogers@northwestern.edu\",\"nickname\":\"\",\"comment\":\"Test from Avalon webapp\",\"_aj_symbol_keys\":[\"name\",\"subject\",\"email\",\"nickname\",\"comment\"]}],\"locale\":\"en\"}",delay_seconds:0,message_attributes:{"message-digest"=>{string_value:"05d7eb129a1aeabcf2df629cb58b31adceb194bb",data_type:"String"},"origin"=>{string_value:"AEJ",data_type:"String"}})  

I, [2017-10-17T22:01:38.589664 #26106]  INFO -- : Enqueued ActionMailer::DeliveryJob (Job ID: 327e07d9-3d6f-4293-b3bb-9b94bec87b4f) to BetterActiveElasticJob(mailers) with arguments: "CommentsMailer", "contact_email", "deliver_now", {:name=>"Carrick Rogers", :subject=>"Technical support", :email=>"carrick.rogers@northwestern.edu", :nickname=>"", :comment=>"Test from Avalon webapp"}
I, [2017-10-17T22:01:38.659116 #26106]  INFO -- : method=POST path=/comments format=html controller=CommentsController action=create status=200 duration=123.06 view=66.88 db=3.02 time=2017-10-17 22:01:38 +0000
```

**Comment by carrickr** [comment]
@mbklein 

CommentMailer is using
`default :to => Settings.email.comments`

Both workers and webapp are reporting that Settings.email.comments to be: `"repository@northwestern.edu"`, so unless we have somewhere further down in SES overriding that we should also be going to the proper place.

**Comment by egilchrist** [comment]
Hello - at 10:08 the following comment was received at repository email  - ""Other" is a pretty big category. I'm not sure I can cover it all in one comment. I guess let's start by seeing if this email goes through."

**Comment by egilchrist** [comment]
Another comment from David came through at 10:46 am

**Comment by davidschober** [comment]
Closing as Done @egilchrist and @jenyoung and @Nic4Images can you make sure we smoke test the form during our Monday morning tests?
