### ISSUE TITLE
add to playlist icon not showing up/ erroring

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#267]
In Staging the "add to playlist" icon is not showing up/ throwing errors. 

To recreate:

- go to http://avr.repo.rdc-staging.library.northwestern.edu/media_objects/h415p953x
- look a the section listings, not the purple box on the right
- click the purple box note the "error"

**Comment by davidschober** [comment]
![screen shot 2017-10-19 at 4 07 33 pm](https://user-images.githubusercontent.com/4803230/31794411-e36055fe-b4e7-11e7-8542-1c18eb3b65a7.png)
![screen shot 2017-10-19 at 4 07 16 pm](https://user-images.githubusercontent.com/4803230/31794412-e36ddfc6-b4e7-11e7-8b1f-a3e742286b2d.png)

**Comment by davidschober** [comment]
@adamjarling @mbklein @carrickr not sure who this would fall to...

**Comment by adamjarling** [comment]
@davidschober I'm not getting an error here.  And I'm fixing the button display issue in another ticket at the moment.   Can you verify this is still an active problem?

**Comment by davidschober** [comment]
I’m still getting an error when not logged in. It seems as if unauthenticated users should be driven to a login page. @mbklein, can you take a look?

**Comment by adamjarling** [comment]
I'm pushing up a fix to core Avalon (for MEJS4) related to this, but doesn't fix this issue sounds like.  I was scratching my head yesterday wondering why no playlists were being returned from the server, when viewing a media object, then realized I wasn't logged in.   

So maybe the question is what should the user see here when not logged in?   Anything?  A stripped-down player?   The add to playlist buttons Brian added should not display guessing?

**Comment by davidschober** [comment]
This is completed, please correct me if I'm wrong @adamjarling @mbklein
