### ISSUE TITLE
load test Avalon on AWS

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#27]
## Description

Before go-live we should load-test avalon on AWS.

## Done looks like

- [x] a realistic load is discussed
- [ ] scripts are written for load testing (do we have a tool for this?)
- [ ] crank is turned

**Comment by davidschober** [comment]
NUIT has licenses for load runner. We could ask them to do a single pass/ help train us up

**Comment by davidschober** [comment]
Can we get time from NUIT? Maybe use bees with machine-guns?

**Comment by davidschober** [comment]
Note, We're using cloud front so traditional load testing gets a bit fuzzy <http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/load-testing.html>

**Comment by Toputnal** [comment]
I'll ask around at NUIT to see who to contact?

**Comment by davidschober** [comment]
Sounds good. I’m trying to see if IU can help out as well.

**Comment by Toputnal** [comment]
I have emailed Christine Lang who Tom Halloran at NUIT indicated was the person to contact for LoadRunner testing.

**Comment by Toputnal** [comment]
@davidschober Do we want to table this for now?  Based upon what @d-venckus said in our last meeting, it doesn't sound like running LoadRunner is really going to tell us anything useful.

**Comment by Toputnal** [comment]
I received this response in regard to load testing Avalon:

James,

The QA team within the PMO of NIT Administrative Systems offers performance and load testing services using LoadRunner from HPE to test enterprise level applications at Northwestern, depending on resource availability.

From what I know of Avalon, it qualifies as an enterprise level application.

I have attached a slide show that we have used to describe our services and how they work and what we look for when engaging with a team that I hope will be helpful to you as we dialog about this potential project.

In general:
- We'd want to know when you planned to go live with the new version of the system.
- We'd want to know what sort of performance expectations you have for the system - what sorts of typical load you expect, peak load expectations, response time hopes, etc.
- We'd want to see an architecture diagram for the system and also get some sense of the technology in play.
- We'd want to understand how the system is used and what parts of it you'd want tested and we'd need to understand the system just well enough to allow us to script those tests.
That's what comes immediately to mind.

The slide show goes into more detail - including a high level description of the steps we follow - and provides our ideal timeline.

After you have a chance to review the slide show please feel free to reach out again and we can decide on next steps.

Steve


--
James R.  Bottino
Senior DevOps SysAdmin
Northwestern University Libraries
Northwestern University
www.library.northwestern.edu
james.bottino@northwestern.edu<mailto:james.bottino@northwestern.edu>
847-491-8389

**Comment by Toputnal** [comment]
Also ping @davidschober  :-)

**Comment by davidschober** [comment]
@Toputnal I added answers above

**Comment by davidschober** [comment]
![avalon_aws](https://cloud.githubusercontent.com/assets/4803230/26696978/32e73276-46d6-11e7-807a-2d40bb5d8971.png)

**Comment by davidschober** [comment]
^^^ infrastructure

**Comment by Toputnal** [comment]
Oh!  Thank you @davidschober your comments posted in-line, and with github's inherent lack of formatting I totally missed them!  I'll write an email response to Steve based upon the answers you provided.  If I have any questions, I'll ping you on #slack.  :-)

**Comment by Toputnal** [comment]
I've emailed Steven A Kahrs <s-kahrs@northwestern.edu> to let him know that we are delaying testing until a later date.

**Comment by davidschober** [comment]
Closing issue. Load testing at this level may prove a bit tricky.
