### ISSUE TITLE
6.2 final prep

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#275]
- [x] Ensure final FE changes are pushed
- [x] setup test canvas
- [x] setup test users 
- [x] testing team discusses spreadsheet. 
- [x] internal run through of whole test script

**Comment by davidschober** [comment]
@mbklein @jenyoung @adamjarling @carrickr FYI!

**Comment by mbklein** [comment]
What are the NetIDs for our test users, and what level of access should each of them have?

**Comment by mbklein** [comment]
Is that in the test spreadsheet?

**Comment by jenyoung** [comment]
@mbklein I'm updating that spreadsheet with Avalon usernames in the NU Vault.

aua6615 - manager role
auh7250 - editor role
auf2249 - depositor role
aum1701 - administrator role

**Comment by mbklein** [comment]
I've added the Manager and Administrator accounts to the top-level groups. Editor and Depositor are collection-level roles, so they'll have to be added (probably by email address, not by netID) when test collections are created.

For reference:

awa6615 = AvalonUser01@example.com
auh7250 = AvalonUser02@example.com
auf2249 =  AvalonUser03@example.com
aum1701 = AvalonUser04@example.com

**Comment by mbklein** [comment]
Canvas Test is set up, and I've installed an SSL certificate so that it more closely mirrors production.
