### ISSUE TITLE
Add items to playlist button displays error when not logged in

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#276]
To Recreate:

go to http://avr.repo.rdc-staging.library.northwestern.edu/media_objects/h415p953x

click on one of the "add items to playlist icon"

See error
![screen shot 2017-11-02 at 11 51 39 am](https://user-images.githubusercontent.com/4803230/32339077-a59fd68a-bfc4-11e7-9acb-561255de9dd9.png)

**Comment by davidschober** [comment]
@adamjarling is this a simple hide if not logged in thing?

**Comment by adamjarling** [comment]
@davidschober Yea, guessing there's a 'logged in' environmental variable somewhere Rails can grab and use to show/hide the toggle button.  Want me to work on this now?

**Comment by davidschober** [comment]
Wow... SC messed me up. I missed this one, sorry @adamjarling. @adamjarling or @mbklein can you slate this for next week (or now if you have time).

**Comment by adamjarling** [comment]
@davidschober @mbklein Is this an issue in core as well, or just NU Avalon?

**Comment by mbklein** [comment]
This is a bug in core, covered by #[2473](https://github.com/avalonmediasystem/avalon/issues/2473)
