### ISSUE TITLE
Notes field generating empty CONTENTS note

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#277]
Newly created records are generating an Notes field with CONTENTS as the only information. It shouldn't display if it's empty

Example: https://media.northwestern.edu/media_objects/ft848q651

In MODS record:
`<note type="general"/>` 

Displays as:

![2017-11-13_130325](https://user-images.githubusercontent.com/2250501/32743812-285672a8-c873-11e7-86ad-5995616a154b.jpg)

**Comment by davidschober** [comment]
@jenyoung this doesn't seem visible from the front end anymore. I think it got sorted in a subsequent upgrade.
