### ISSUE TITLE
Summary field has different look than rest of record

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#278]
The summary field has a different look than the rest of the record - it should be the same correct?

https://media.northwestern.edu/media_objects/ft848q651

![2017-11-13_130648](https://user-images.githubusercontent.com/2250501/32743942-9a7eb958-c873-11e7-8e9f-08c59923b4ae.jpg)

**Comment by davidschober** [comment]
@adamjarling did this get merged?

**Comment by adamjarling** [comment]
@davidschober Yes, looks like MBK merged this PR yesterday afternoon to `deploy-aws-staging`.

**Comment by davidschober** [comment]
Cool. I'll look and close it.
