### ISSUE TITLE
Launch simian army attack

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#285]
## Description

As we move toward building more bulletproof systems, we should investigate ways to thoroughly test our infrastructure. Luckily the good folks at Netflix open sourced their angry monkeys for the world to use. I suggest we setup staging to replicate prod w/r to number of instances and let loose the mad creatures.

https://github.com/Netflix/SimianArmy/wiki/Chaos-Monkey

## Done looks like
- simian army is set up
- staging is set up to replicate prod in number of instances if different
- chaos monkey is let loose
- we watch alarms and (hopefully) self healing happen. 
- issues are written to add more armor if the simian army succeeds in its angry quest.

**Comment by egspoony** [comment]
Abandoned!
