### ISSUE TITLE
Batch ingest issues, staging, 6.2

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#288]
created collection on staging `jen_test_12_13_2017

Uploaded to staging dropbox items from below after untarring 
http://www.avalonmediasystem.org/downloads/DemoFixturesBatch.tar.gz

edited spreadsheet, added my email, removed transcoding to Yes

collection not ingested, no .error spreadsheet in file listing, no error or confirmation emails received.

**Comment by davidschober** [comment]
I'll try to recreate this.

**Comment by davidschober** [comment]
``` I, [2017-12-13T18:13:17.885441 #24140]  INFO -- :
Sent mail to david.schober@northwestern.edu (124.2ms)
I, [2017-12-13T18:13:17.885572 #24140]  INFO -- : Performed BatchIngestJob from BetterActiveElasticJob(batch_ingest) in 5883.31ms
F, [2017-12-13T18:13:17.886342 #24140] FATAL -- :
Aws::SES::Errors::MessageRejected (Email address is not verified. The following identities failed the check in region US-EAST-1: avalon-notifications@repo.rdc-staging.library.northwestern.edu, david.schober@northwestern.edu):
  app/jobs/batch_ingest_job.rb:34:in `rescue in perform'
  app/jobs/batch_ingest_job.rb:26:in `perform'
````

We need to be sending from an email address that is whitelisted and verified. @mbklein, should we send from the same as prod? That seems OK to me.

**Comment by davidschober** [comment]
We will use repository@northwestern.edu . It needs to be setup and verified.

**Comment by davidschober** [comment]
I was able to get batch to ingest (MBK is handling the final steps to get email verification to work). However media is not attaching. The items are created and the error "no media is associated with this item" is shown.
![Screen Shot 2017-12-13 at 1.01.44 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57113db3779ed80e00620458/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f06b7191a379f1122a4f5b5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d66e0c74cf3416a4ba8717b709e8208a4ed6b3bb8f45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df748e04454ac113661e5712431.png)

**Comment by davidschober** [comment]
@mbklein ^^

**Comment by davidschober** [comment]
@mbklein @carrickr 

Tested today and got an email... It errored with the following : 


```
Begin forwarded message:

From: repository@northwestern.edu
Subject: Failed batch ingest processing errors for: Avalon Demo Batch
Date: December 14, 2017 at 4:02:28 PM CST
To: david.schober@northwestern.edu

/
Initial processing of your batch ingest failed. Details are below. Please see the Batch Ingest Package Format for further help.

Manifest file: s3://avr-masterfiles-staging-rd56wk8/dropbox/David_Canvas/Demo_Manifest.xlsx

NoMethodError: undefined method `close' for #<Addressable::URI:0x00007fa71eab8bd8> Did you mean? clone
```

**Comment by davidschober** [comment]
@jenyoung I'm going to abandon this. We are going to regroup on 6.3 as batch is completely rewritten.
