### ISSUE TITLE
Make 6.3's Batch Ingest Work with S3 Triggers

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#289]
So it works on our AWS environment with S3 buckets.

**Comment by davidschober** [comment]
@carrickr and @mbklein is 6.3 going to be a big upgrade or will it be straight forward? This sounds like we might have to do more rewriting...

**Comment by carrickr** [comment]
I think we will need to do some rewriting.  I also there is the potential we could move this to the core board.  IU is going to want this for their AWS when they shut down pawpaw and some of their other servers in favor of AWS.   

We might be able to slate this either as a 6.3.1 type of deal where this goes into Core.  Phuong has some interest in this for the IU side so mbk, myself, and Phuong (or some combo thereof) can work to rewrite the code so it does both local file system and S3 Triggers.  The issue there is doing it in a non ugly way where both work.  Right now on the NU side we just rip out and replace stuff, if we support both you get into ugly code with `if local_system .... elseif S3....`.  So having both supported while keeping code quality there takes a bit of effort.  I've talked about this with Chris and neither of us could talk out an easy way to do it, so yeah bit of time on architecting and planning.

We can rapidly deploy 6.3.1 since the only change would be S3Batch and test 6.3.1 on our staging servers with Course Reserve's back.

**Comment by davidschober** [comment]
@carrickr I think you're working on this... moving to in progress.
