### ISSUE TITLE
Pass cookies to HLS over XHR

### ISSUE THREAD

**Issue by mbklein** [nulib/avalon#314]
`hls.js` does not pass credentials (headers, cookies, tokens) over XHR by default. It has to be configured to do so.

### Expected Behavior ###
* Browser is authorized to retrieve HLS playlists and streams

### Observed Behavior ###
* Safari, with native HLS support, works fine
* Chrome, using the MediaElement -> DailyMotion HLS shim, is not authorized

**Comment by adamjarling** [comment]
This is fixed for NU, but should go into core Avalon.  Details to follow...
