### ISSUE TITLE
Adding item to playlist errors

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#316]
## Description

When adding a full item to a playlist it errors with "ERROR: End time must be between start time and end of section" Even though the end time is identical to the end time of the media object

to recreate;

1. go to https://avr.repo.rdc-staging.library.northwestern.edu/media_objects/12579s27c
2. click on the "add to playlist" icon
3. see error attached

**Comment by davidschober** [comment]
![Screen Shot 2018-01-05 at 4.19.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57113db3779ed80e00620458/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454f66b7191a37cf113224f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ee5d66e0c74cf3416a4ba8717b709e8208a4ed6b3bb8f45d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ee04454a1163f67ef7e2431.png)

**Comment by davidschober** [comment]
Note, this doesn't seem to be happening on CORE.

**Comment by carrickr** [comment]
Works if you do 9.56 for the time, so it's some kind of time and rounding error?

**Comment by carrickr** [comment]
Yup, if you look at duration, the duration from Amazon is 596000 milliseconds, which is 596 seconds and 60(596/60-9) is 56

**Comment by carrickr** [comment]
@adamjarling do you have any thoughts on why the player is taking 596000 and getting 9:57?  Our checks in javascript are based off that time and the player shows 9:57 as duration

**Comment by carrickr** [comment]
I assume the player is doing the math in `mejs4_helper_time_rail.es6`, but it seems like we do the math multiple places so I'm not sure where the proper place is to look.

**Comment by adamjarling** [comment]
@carrickr Taking a look now...

**Comment by davidschober** [comment]
@adamjarling did you mean to assign this one to me?

**Comment by davidschober** [comment]
@carrickr @mbklein I'm ok adding a cushion, but part of me wants to wait to see if we see this anywhere else

**Comment by carrickr** [comment]
@davidschober This is assigned to you to decide if this can be marked closed for the sprint or if you want the cushion now, your call as PO
