### ISSUE TITLE
Document How to Upload a DIL Share to an AVR Dropbox on S3

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#318]
For collection managers wanting to do batch ingest.  If they have to use cyberduck on their machine as a go between it can take days.

**Comment by davidschober** [comment]
@carrickr are you imagining that we have a  job-runner machine that's hooked up to an isilon share for side-loading? Like if I have 10k images I want to upload, I drop them off on "isilon/s3-sideload-bucket" which is mounted from some vm. The VM runs a cron job that syncs up to the s3 bucket asynchronously?

**Comment by davidschober** [comment]
closing as stale.
