### ISSUE TITLE
Create Arks for records with preexisting handles

### ISSUE THREAD

**Issue by csyversen** [nulib/avalon#329]
### Description
MBK can probably flesh out this issue a bit more, but it's my understanding that records in Avalon that already had handles created for them weren't given Arks as well. We'll need to create Arks for all records in Avalon.

related to #185

### Done Looks Like
- Arks are created for all records in Avalon.

### Tasks
- [ ] Figure out how to not tax the worker
- [ ] Create Rogue 2 worker possibly

**Comment by davidschober** [comment]
Moving to Ready this will be after 6.3.2

**Comment by davidschober** [comment]
superseded by #447
