### ISSUE TITLE
Create Avalon 6.x fork/GH to customize

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#33]
## Description

We need to either create a new GH repo or update the current 4.x gh repo/fork (this one here!). This should be done ASAP so Adam can start to work on customizing avalon.

**Comment by davidschober** [comment]
@mbklein by the chatter it sounds like this is in progress.

**Comment by davidschober** [comment]
This is done.

**Comment by carrickr** [comment]
https://github.com/avalonmediasystem/avalon/tree/6.x-aws-s3
