### ISSUE TITLE
Creating new playlist throws "something wrong with this playlist"

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#330]
## Description

Creating a new playlist errors with We're sorry, but something went wrong.

## To Recreate:

- Create a new playlist
- https://avr.repo.rdc-staging.library.northwestern.edu/playlists/new
- add info, click create
- see that it errors with "We're sorry, but something went wrong."
- go back to playlist listing page
- see that page was created https://avr.repo.rdc-staging.library.northwestern.edu/playlists
- try to go to the playlist and see that it errors with same error.

**Comment by carrickr** [comment]
This page is gone from 6.3.2:

https://github.com/nulib/avalon/blob/deploy-aws-prod/app/views/nu_playlists/item_list.html.erb

Asked @adamjarling if we need his custom skinned item or if we can revert back to the regular item partial.  Action will be taken based on which is desired.

**Comment by carrickr** [comment]
@davidschober ready for retest

**Comment by davidschober** [comment]
OK. This is still happening. To recreate go to playlists:

http://avr.repo.rdc-staging.library.northwestern.edu/playlists

and click on any playlist.

**Comment by davidschober** [comment]
Update. This is happening for newly created playlists. Old playlists seem to be working. Now I'm confused.

**Comment by carrickr** [comment]
Can't reproduce, I think you just had some weirdness due to testing during the deploy out of a new EC2 instance.  Boxes were just finishing their swap at the time you were testing.
