### ISSUE TITLE
Current Section arrow missing from media object page

### ISSUE THREAD

**Issue by mbklein** [nulib/avalon#335]
### Description
The arrow is missing from the "sections" list on http://avr.repo.rdc-staging.library.northwestern.edu

To recreate:
- Go to an item with lots of sections http://avr.repo.rdc-staging.library.northwestern.edu/media_objects/jd472w90n
- note that the listing does not have the little arrow (see screenshot below)

### Done Looks Like
- Selected arrow works as expected in production.

### Tasks
- [x] Compare local dev to production environment, figure out the issue
- [x] Fix it.

**Comment by adamjarling** [comment]
@davidschober Can you post a public production url from above where I can inspect it working?

**Comment by mbklein** [comment]
See avalonmediasystem/avalon#2780.

**Comment by davidschober** [comment]
This is added back to sections. I kicked off  #347 as n playlists the arrow marker is too close to the numerics @adamjarling
