### ISSUE TITLE
Playlist marker arrow too close to text 

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#347]
## Description

the playlist marker arrow is too close to the playlist item text. It lays over the top of the numerical. 

## image
![screen shot 2018-01-30 at 1 42 25 pm](https://user-images.githubusercontent.com/4803230/35587995-fb6512d8-05c4-11e8-9771-025abafa6e23.png)

**Comment by adamjarling** [comment]
Yea, guessing so.  Can you post a live URL so I can play with it?

**Comment by adamjarling** [comment]
@davidschober This was fixed, yea?

**Comment by davidschober** [comment]
yes. Closing
