### ISSUE TITLE
Bring In (AND TEST!) Avalon Speedups from Core

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#348]
Probably do this after 6.3 goes live, given how close to the deadline we are.

Commits:

https://github.com/avalonmediasystem/avalon/commit/c57f8f62801611699e8ef0dd117e752f7bd3c10e

https://github.com/avalonmediasystem/avalon/commit/74d9b9d54bb684befbfe5e229ed6dacd7cb4c682

Bring it into staging and test with large section items and then push out to prod sometime after the Fedora upgrade.

**Comment by davidschober** [comment]
@carrickr did this get done? I think you said you did...

**Comment by davidschober** [comment]
@carrickr should moving to in progress and "on hold" until after we move the 16k over.
