### ISSUE TITLE
playlists clips can't grab streams in chrome or FF

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#351]
## Description 

playlists can't grab stream clips for some items in FF or Chrome.

In Staging, I'm able to create playlists with full items and clips for some items. Others do not seem to work at all. In production all times in a playlist on Chrome or FF show start and end times of 0:00 -->0:00 whether clips or not

https://avr.repo.rdc-staging.library.northwestern.edu/playlists/23

To Recreate:

- create a playlist
- add items to a playlist
- see that items can not stream

![screen shot 2018-02-06 at 10 33 29 am](https://user-images.githubusercontent.com/4803230/35872106-938cc3e2-0b2b-11e8-991d-b3252813772d.png)
![screen shot 2018-02-06 at 10 34 36 am](https://user-images.githubusercontent.com/4803230/35872107-9396e66a-0b2b-11e8-8e03-0256108a2f7b.png)
![screen shot 2018-02-06 at 10 46 11 am](https://user-images.githubusercontent.com/4803230/35872109-93bee66a-0b2b-11e8-88ba-6fb319de4412.png)

**Comment by davidschober** [comment]
## NOTE this also seems to be occurring on canvas

 
So another issue, very similar… I’m trying to link this newly loaded video, Mike Figgis’ Hotel <http://media.northwestern.edu/media_objects/vq27zp32q>, to a class.  In Avalon it works, the time lapse bar showing 00:00 to 01:51:24.  But in Canvas, it doesn’t work.  Instead, the same as below is happening.  The time lapse bar shows 00:00 to 00:00, and when I click play, the icon circles and nothing plays.  I’ve tried it in both Chrome and Firefox and it’s happening in both.  Is this all something to do with this morning’s upgrade?  Should I hold off on this stuff until a certain time today?  Please let me know.  Thanks!
 
 -----


I just got a request from a professor to link “Prime Time / Desnick Eye Center” <http://media.northwestern.edu/media_objects/kw52j808s> to his course.  I’ve linked it up, but it isn’t working.  The time lapse bar shows 00:00 to 00:00, and when we click play, the icon circles and nothing plays.  The prof needs this for a class tomorrow morning.  Is the content retrievable?  Can it be relinked to this Avalon item today?  (I’m guessing this might have something to do with this morning’s upgrade and hoping it’s an easy quick fix).  Please let me know.
 
Thanks!
 
Molly

**Comment by davidschober** [comment]
Example of a playlist in canvas with two working and one working 

https://canvas.northwestern.edu/courses/47583/modules/items/921326

**Comment by davidschober** [comment]
When a playlist item can't play, it shows no  item details

![screen shot 2018-02-06 at 11 25 56 am](https://user-images.githubusercontent.com/4803230/35873901-bce1a366-0b30-11e8-8049-a7539c6ce271.png)


In safari, it shows fine. 

![screen shot 2018-02-06 at 11 26 00 am](https://user-images.githubusercontent.com/4803230/35873910-c11105da-0b30-11e8-8041-cba6beeb3915.png)

**Comment by davidschober** [comment]
Just for notes, did you also have to invalidate the cloud front cache?

**Comment by mbklein** [comment]
Yes, but that was a known issue and I had already done so.

**Comment by davidschober** [comment]
Moving to close.
