### ISSUE TITLE
Pinwheel spins forever on clips

### ISSUE THREAD

**Issue by druparrish** [nulib/avalon#354]
Minor threat:
When playing a clipped video on a playlist, the clip will pinwheel you to death. It plays if you click the play button, but you might sit there for a while thinking it's not done loading. 

Full videos uploaded to playlists do not suffer from this, nor does it seem to happen when you add a clip to a playlist as a canvas user. 
![untitled](https://user-images.githubusercontent.com/25689480/35876481-0aad9350-0b38-11e8-9849-08285398bdb9.png)

## To Recreate

- Go to a playlist in chrome  https://avr.repo.rdc-staging.library.northwestern.edu/playlists/23
- click on an item which is not the starting item
- see that the in progress item spins
- click the play button in the rail
- see that the item plays.

**Comment by davidschober** [comment]
This is fixed
