### ISSUE TITLE
Confirm certain files on farchive

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#356]
### Description
Carolyn asked me to confirm some course reserve video files are on farchive so that we can clear them from Isilon storage. Attaching .txt file containing all the filenames I'd like to confirm have made it to farchive

### done looks like
- [ ] confirm files on this list are on farchive
- [ ] let Laura know yes or no

**Comment by laura-alagna** [comment]
[filenames_to_confirm_on_farchive.txt](https://github.com/nulib/avalon/files/1704617/filenames_to_confirm_on_farchive.txt)

**Comment by laura-alagna** [comment]
@davidschober let me know if you have questions about this

**Comment by laura-alagna** [comment]
@carrickr do you have time to do this this week maybe?

**Comment by davidschober** [comment]
@laura-alagna this one slipped through the cracks a bit. Let's talke about priority on this.
