### ISSUE TITLE
Strip Brackets from Titles in Northwestern University School of Music Concert Recordings

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#360]
Strip out the [ and ] that are getting pulled in when the title is retrieved from Alma.

Do this after #357 is done so we can just do it one pass.

**Comment by carrickr** [comment]
```solr = RSolr.connect url: Settings.solr.url
r = solr.get 'select', params: {q: 'collection_ssim:Northwestern University School of Music Concert Recordings', rows: 100000}
docs = r['response']['docs']
docs.each do |d|
  mo = MediaObject.find(d['id'])
  mo.title = mo.title.tr('[]','')
  mo.save!
end```

**Comment by jenyoung** [comment]
FYI this is a cataloging practice and it means something. I'm totally OK with removing them, but I can see more AVR ingests having them in the future. I don't know if you want to add it as part of the process or just do it when we see it.

**Comment by carrickr** [comment]
@jenyoung I was actually removing them because @laura-alagna thought the brackets would annoy.  If in the future you're fine with having them displayed to end users I can leave them be

**Comment by carrickr** [comment]
Also this is now done
