### ISSUE TITLE
check for any unprocessed master files once 16k are uploaded

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#361]
to be done post #357 

In console:

```
solr = RSolr.connect url: 'http://solr.repo.vpc.rdc.library.northwestern.edu/solr//avalon'
r = solr.get 'select', params: { q: "status_code_ssi:FAILED", rows: 100000}
docs = r['response']['docs']
```
Docs should have a size of zero, if we don't it means transcoding failed for some reason, likely too many parts posting at the same time and messing up Elastic Transcode, run:

```
docs.each do |d| MasterFile.find(d['id']).process end
```

to reprocess those files

**Comment by carrickr** [comment]
Done for the current batch, but we'll need to rerun this after the next import

**Comment by davidschober** [comment]
@carrickr I thought I heard you say this got done. Should we close? Moving to review.

**Comment by laura-alagna** [comment]
Greg needs to let us know how he wants the failed transcode ones to display, i.e. leave as is, put in a "dummy" file, etc. Either way need to have a note added to the metdata
