### ISSUE TITLE
Deal With Non Transcodeable Media Object

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#362]
Media Object: https://media.northwestern.edu/media_objects/v979v309v
Reason: No file on S3
Creator: t-oconnell3@northwestern.edu

Looks deletable, but we should verify.

**Comment by davidschober** [comment]
Not sure I understand what the deal is with this one? Who uploaded it?

**Comment by jenyoung** [comment]
it's a course video but tom shouldn't be uploading them

**Comment by davidschober** [comment]
so @jenyoung is this deletable? It doesn't look real and there's no associated file.

**Comment by davidschober** [comment]
@Nic4Images can you confirm this is deletable? it looks like an odd test that broke. cc: @carrickr

**Comment by davidschober** [comment]
@carrickr we're good to delete.

**Comment by davidschober** [comment]
Deleted and done.
