### ISSUE TITLE
Fix GA Code

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#364]
## Description

It looks like the GA code dropped off avalon?

We're reading no-traffic from GA. 

## Done looks like

- GA code is added back 
- GA is tested and works 

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-797260-33"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-797260-33');
</script>
```

**Comment by carrickr** [comment]
https://github.com/nulib/avalon/commit/da89e8e84fef316399c381fb6cf373badb1cd6f8

**Comment by carrickr** [comment]
@davidschober Script is back, want to verify it is working?

**Comment by davidschober** [comment]
verified that it's there and working as expected.
