### ISSUE TITLE
Investigate problems with catalog records for School of Music Recordings

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#368]
broke this one off of #367

## Details
During ingest some of the School of Music Recordings threw errors that seem to be a result of problems with the catalog records in Alma. 
They are listed on this spreadsheet on the Alma tab: 
https://docs.google.com/spreadsheets/d/1hZQMPp6yd6Qt9rQv59qYrhKwCJCKmM5MQeJu5ddlW3U/edit?usp=sharing

## Done looks like
- [x] @jenyoung looks into these errors to see what the problems are
- [x] @jenyoung fixes the issues (or lets me know who I need to get in touch with to have the records updated)

**Comment by jenyoung** [comment]
all fixed. there are two records highlighted on the sheet that seem to be ok. i didn't see the errors in the ALMA records and was able to import the on staging with no errors.

**Comment by laura-alagna** [comment]
awesome! thanks @jenyoung. Closing this issue
