### ISSUE TITLE
Replay of batch ingest not being picked up.

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#370]
Batch ingested Cichowicz collection, 10 works made it in fine.

Errors I fixed. Uploaded correct files. 
`
Row | Error
-- | --
3 | Date issued ( 1982-06-29) is in wrong format.
4 | Date issued ( 1982-06-30) is in wrong format.
14 | Content File not found:   s3://avalon-masterfiles-cfx3wj9/dropbox/Vincent_Cichowicz_Master_Class_Audio_Archives/inu-cichow_am_T250v1354A_a.wav   and Content File not found: s3://avalon-masterfiles-cfx3wj9/dropbox/Vincent_Cichowicz_Master_Class_Audio_Archives/inu-cichow_am_T250v1354A_b.wav
`

 corrected and reuploaded batch spreadsheet with the proper renaming -and nothing is being ingested.

`To replay this batch, please rename your spreadsheet to faac5ccf-8765-4812-a62f-1cb88df2bbee_cichowicz_ingest_metadata.xlsx and reupload it after making desired changes. Only unpublished items can be updated via this method. Retain all rows in the spreadsheet including those that have no changes.****`

**Comment by carrickr** [comment]
@jenyoung Can you upload the replay sheet you used please?

**Comment by carrickr** [comment]
```
{"id":1833,"batch_registries_id":7,"payload":"{\"title\":[\"Trumpet Master Class 1982-07-03\"],\"creator\":[\"Cichowicz, Vincent\"],\"genre\":[\"Music Master Class\"],\"date_issued\":[\"1982-07-03\"],\"geographic_subject\":[\"Regenstein Hall of Music (Evanston, Ill.)\"],\"table_of_contents\":[\"Track 1. Excerpt: Goldenberg und Schmuyle (from Pictures at an Exhibition) -- Excerpt: Ravel Piano Concerto in G -- Excerpt: Pines of Rome offstage solo -- Excerpt: Petrushka (Ballerina dance and waltz) -- Excerpt: Parsifal (prelude) -- Excerpt: Lieutenant Kijé Suite (movement 3) -- Excerpt: Pictures opening Promenade solo -- Excerpt: Gershwin Piano Concerto in F. Track 2: Excerpt: Pines of Rome offstage solo -- Excerpt: Lieutenant Kijé Suite -- Excerpt: Leonore Overture no. 3 -- Excerpt: Mahler 5 opening.\"],\"note_type\":[\"local\",\"performers\"],\"note\":[\"T250 v.1078\",\"Track 1: Yirum, Dale, Mickey, and Frank. Track 2: Anne, Jim Elsmick, Dan Smith, Fraser. \"]}","complete":false,"error":true,"current_status":"registered","error_message":"To successfully ingest, either title and date issued must be set or a bibliographic id must be provided","media_object_pid":null,"position":2,"created_at":"2018-02-28T23:24:34.838Z","updated_at":"2018-03-01T15:32:01.789Z"}
{"id":1843,"batch_registries_id":7,"payload":"{\"title\":[\"Trumpet Master Class 1983-07-05\"],\"creator\":[\"Cichowicz, Vincent\"],\"genre\":[\"Music Master Class\"],\"date_issued\":[\"1983-07-05\"],\"topical_subject\":[\"Beethoven, Ludwig van, 1770-1827\",\"Bordogni, Marco, 1789-1856\",\"Arban, J.-B. (Jean-Baptiste), 1825-1889\",\"Clarke, Herbert L. (Herbert Lincoln), 1867-1945\"],\"geographic_subject\":[\"Regenstein Hall of Music (Evanston, Ill.)\"],\"table_of_contents\":[\"Track 1. Discussion of playing and practice techniques -- Getchell studies played -- Leonore Overture no. 3 played. Track 2: Clarke Technical Studies played -- Various Arban studies played -- Bordogni study played.\"],\"note_type\":[\"local\",\"performers\",\"general\"],\"note\":[\"T250 v.1230\",\"Track 1: Jim Cleasner, John Scott, Natalie Watowick, Hikihiro Sekiama, Sandra Kingsford, Dan Picarillo. Track 2: Natalie Watowick and John Scott.\",\"Track 1: People present \\\"under the D-30 assignment\\\": Robin Cameron, Parthena Rigsby, and Roberto Rivera. NU masters student recitals given later in the week: Janice Hoffman and Bruce Briney.\"]}","complete":false,"error":true,"current_status":"registered","error_message":"To successfully ingest, either title and date issued must be set or a bibliographic id must be provided","media_object_pid":null,"position":12,"created_at":"2018-02-28T23:24:35.430Z","updated_at":"2018-03-01T15:32:01.794Z"}
{"id":1832,"batch_registries_id":7,"payload":"{\"title\":[\"Trumpet Master Class 1984-07-13\"],\"creator\":[\"Cichowicz, Vincent\"],\"genre\":[\"Music Master Class\"],\"date_issued\":[\"1984-07-13\"],\"topical_subject\":[\"Stravinsky, Igor, 1882-1971\",\"Mahler, Gustav, 1860-1911\",\"Prokofiev, Sergey, 1891-1953\",\"Beethoven, Ludwig van, 1770-1827\",\"Respighi, Ottorino, 1879-1936\",\"Mussorgsky, Modest Petrovich, 1839-1881\",\"Tchaikovsky, Peter Ilich, 1840-1893\"],\"table_of_contents\":[\"Track 1, Part 1: Excerpt: Petrushka (Ballerina Dance and Waltz) -- Excerpt: Mahler 5 opening -- Excerpt: Lieutenant Kijé Suite -- Excerpt: Leonore Overture No. 3 -- Excerpt: Pines of Rome offstage solo -- Excerpt: Pictures opening Promenade solo. Track 1, Part 2: Excerpt: Pictures opening Promenade solo (appears twice) -- Excerpt: Mahler 5 opening -- Excerpt: Pines of Rome offstage solo -- Excerpt: Leonore Overture No. 2. Track 2, Part 1: Excerpt: Pictures opening Promenade solo (appears twice) -- Excerpt: Capriccio Italien -- Excerpt: Lieutenant Kijé Suite -- Excerpt: Mahler 5 opening -- Excerpt: Danse Napolitaine from Swan Lake\\n-- Excerpt: Petrushka (Ballerina Dance and Waltz). Track 2, Part 2: Excerpt: Mahler 5 opening  -- Excerpt: Pictures opening Promenade solo.\\n\"],\"note_type\":[\"local\",\"performers\"],\"note\":[\"T250 v.1355\",\"Track 1, Part 1: Jim, Sean/John. Track 1, Part 2: Linda Brown.\"]}","complete":false,"error":true,"current_status":"registered","error_message":"To successfully ingest, either title and date issued must be set or a bibliographic id must be provided","media_object_pid":null,"position":1,"created_at":"2018-02-28T23:24:34.815Z","updated_at":"2018-03-01T15:17:31.110Z"}
```

Looking at the created and updated times, it looks two attempts were made, so the sheet did pick up and run, but whatever is going on still has three where it thinks the sheet lacks needed info.

```
created_at":"2018-02-28T23:24:35.430Z","updated_at":"2018-03-01T15:32:01.794Z"
created_at":"2018-02-28T23:24:34.838Z","updated_at":"2018-03-01T15:32:01.789Z"
created_at":"2018-02-28T23:24:34.815Z","updated_at":"2018-03-01T15:17:31.110Z"
```

**Comment by jenyoung** [comment]
yeah, now the error message tells me that my spreadsheet is empty. I open it up and all my data is there.
[faac5ccf-8765-4812-a62f-1cb88df2bbee_cichowicz_ingest_metadata.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57914aa192706c13005d758f/125516c66e82c728ace21e0d46ee959b20d780aa89a4e714f208bdc07117753e2852f12d3dd4e02ae71a7f075d0d1cf914370c1dafa1d66cffe5761fd3025cb892293029937940f8e9c64ead1da860c910dfe3efce5ecafa382de088dc4f371702108bfa553da8cb4bc959a54ee6485cb60f2421b72862231acd54206e796d34aafbd557828760a4ba182851cde3e7fd045f.xlsx)

**Comment by carrickr** [comment]
@jenyoung 

Github is doing something weird with your file and having it download as `125516c66e82c728ace21e0d46ee959b20d780aa89a4e714f208bdc07117753e2852f12d3dd4e02ae71a7f075d0d1cf914370c1dafa1d66cffe5761fd3025cb892293029937940f8e9c64ead1da860c910dfe3efce5ecafa382de088dc4f371702108bfa553da8cb4bc959a54ee6485cb60f2421b728622.xlsx` vs `faac5ccf-8765-4812-a62f-1cb88df2bbee_cichowicz_ingest_metadata.xlsx` the which is too long of a filename.  Could you rename it to something simple like `a.xlsx` and reupload it please?

Bad github!

**Comment by jenyoung** [comment]
oh that's weird.
[a.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57914aa192706c13005d758f/125516c66e82c728ace21e0d46e9d6d6619291a685ecbc57e607b2c171117470795dfa7c28d7b670e71a79515e5e1da9465d5656e0ebcb7af8e2632dd3165eafc3674d75cf3710a9ba821fbf08bc218d4981b5aec7.xlsx)

**Comment by carrickr** [comment]
Thanks,  I think I see what happened

**Comment by carrickr** [comment]
@jenyoung I think you're going to do have to do the last three by hand or totally recreate the sheet, the sheet itself is somehow messed up (not sure if encoding or what) and I'm not able to force it into a good form.  The bug is those three rows are loading incorrectly into Avalon and it all goes downhill from when Avalon tries to parse the sheet.

**Comment by carrickr** [comment]
Also just as a note, in A1 you need the full name `Vincent Cichowicz Master Class Audio Archives` not just `Cichowicz`, that wasn't the root cause of the problem but that contributed to multiple error states occurring.

**Comment by jenyoung** [comment]
thanks @carrickr for looking into this. I imported the last 3 works via the single-item inteface.
