### ISSUE TITLE
I have too many selected items

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#371]
Somehow in Avalon I have 585 items selected (I don't remember when this happened...) and when I click "manage selected items" to see them or unselect, the page won't load.

tried on Firefox and Chrome. 
<img width="1281" alt="screen shot 2018-03-01 at 11 22 18 am" src="https://user-images.githubusercontent.com/25389954/36859039-d741d658-1d42-11e8-8b33-dc6dbca6d137.png">

**Comment by carrickr** [comment]
```
irb(main):011:0> User.where(email: 'laura.alagna@northwestern.edu').first.bookmarks.all.size
=> 585
irb(main):012:0> User.where(email: 'laura.alagna@northwestern.edu').first.bookmarks.delete_all
=> nil
irb(main):013:0> User.where(email: 'laura.alagna@northwestern.edu').first.bookmarks.all.size
=> 0
```

Should be cleared now @laura-alagna
