### ISSUE TITLE
[Avalon] clean up files after ingestion

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#373]
## Description

We realized that as an artifact of our migration to AWS, we are not moving ingested master files to "permanent" AWS storage. We should be following a similar pattern to our previous Avalon install where master files were moved to a PID-based structure after ingestion. 

## Done looks like:

- [x] files are moved from "dropbox" to permanent location and dropped into the preservation folder and prefixed with pid ingestion. 
- [ ] current master files in "dropbox" are moved to proper place. 
## questions

should this just reuse the "uploads" directory in the master files bucket?

**Comment by davidschober** [comment]
@carrickr can you put a brief update when you feel confident about the status?

**Comment by carrickr** [comment]
Console code

```
s = RSolr.connect url: 'http://solr.repo.vpc.rdc.library.northwestern.edu/solr//avalon'
r = (s.get 'select', params: {q: 'has_model_ssim:MasterFile', rows: 9999999})['response']['docs']

fix_list = []
r.each do |mf|
  fix_list << mf if mf['migrated_from_ssim'].blank?
end

fix_list.each do |i|
  if FileLocator.new(i['file_location_ssi']).exist? && !i['isPartOf_ssim'].blank?
    new_location = "s3://preservation-cfx3wj9/avalon-masterfiles/#{i['isPartOf_ssim'].first}/#{i['file_location_ssi'].split('/').last}"
    cmd = "aws s3 cp #{i['file_location_ssi']} #{new_location}"
    system(cmd) unless FileLocator.new(new_location).exists?
  end
end

not_found = [] 
fix_list.each do |i|
  if (i['file_location_ssi'].include? 'avalon-masterfiles-cfx3wj9') && (FileLocator.new(i['file_location_ssi']).exists?) && (!i['isPartOf_ssim'].blank?)
    old_location = i['file_location_ssi']
    new_location = "s3://preservation-cfx3wj9/avalon-masterfiles/#{i['isPartOf_ssim'].first}/#{i['file_location_ssi'].split('/').last}"
    not_found << i unless FileLocator.new(new_location).exists?
  end
end
```

**Comment by carrickr** [comment]
Many of the files in question are in Chicago Chamber Musicians and we are having an issue stemming from a fact there is `,` in the directory name.  I am currently writing a custom script to handle those.  I will update with a missing count after that.

**Comment by carrickr** [comment]
As of 10:45 Central on April 25th, all new content is moved with the following pattern:

`s3://preservation-cfx3wj9/avalon-masterfiles/1z/40/kv/20/1z40kv20z/bunny.mp4`

The `1z/40/kv/20/1z40kv20z/` is the default Avalon way for breaking the pid up.  I don't love it, but better to stick to the standard core practice.

**Comment by carrickr** [comment]
Chambers list should hopefully represent most of the ~2,800 master files that didn't copy to S3 on the first pass.  Total size of Chambers is ~3,200 although not all of them have the `,` escaping issue.

**Comment by davidschober** [comment]
cool.
