### ISSUE TITLE
Thumbnail not updating

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#378]
## Description
 
I’m adding a video to the Repository and can’t get the thumbnail selection to work.  It’s this item https://media.northwestern.edu/media_objects/jd472x96h .  When I click on the camera to select the poster/thumbnail image, the image doesn’t pop up (as usual) with the “Update Poster Image” screen.  Although, I see that the time stamp for the image I chose is saved under “Thumbnail” on the “Manage file(s)” screen.  Could this be a quick fix?  I have some more videos to add and do this for this afternoon.  Please let me know.
 

## to recreate

* go to https://media.northwestern.edu/media_objects/jd472x96h 
* click on thumb creator
* see that the thumbnail is not updated. 
* Note, a different object updates fine https://media.northwestern.edu/media_objects/jq085k837

**Comment by carrickr** [comment]
MasterFile is not on s3, I'd need the user to send it to me to examine.
