### ISSUE TITLE
Discuss Implications of the new MasterFile Move Strategy

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#379]
https://wiki.dlib.indiana.edu/display/VarVideo/Managing+Master+Files

As noted there is only a move and delete, no copy.  The move then breaks batch replay in the sense the source files are not there to replay.  We either need to add a `copy` strategy to Avalon 6 core and bring it into NU or else educate our users about this.

**Comment by davidschober** [comment]
I think we can educate.

**Comment by davidschober** [comment]
Second thought. Maybe we life cycle them

**Comment by carrickr** [comment]
@davidschober life cycle isn't on the table without code changes, since Avalon has explicit code to delete the file in the move job

**Comment by davidschober** [comment]
OK. I'm good with the move and delete strategy. And I think it makes sense that if you need to/want to replay it will take a repush. Moving to close.
