### ISSUE TITLE
Verify staging is following same move strategy

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#384]
## Description

We should verify that Avalon staging is using the same move strategy as production. I didn't see the bucket.

## Done looks like

- move strategy is verified as the same between production and staging.

**Comment by davidschober** [comment]
@carrickr can you verify we're using the same move strategy on Staging as in Production? I didn't see the bucket in staging. If I'm misunderstanding something, let me know.

**Comment by davidschober** [comment]
@carrickr can you just give me the Yup, it's working the same way and point me to the bucket?

**Comment by carrickr** [comment]
files on staging use the move strategy and end up in avr-masterfiles-staging-rd56wk8/preservation

**Comment by davidschober** [comment]
Thanks !
