### ISSUE TITLE
Error message when creating new collections on AVR staging

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#388]
This bug encountered when testing on Avalon staging.

Logged in with NetID aua6615. As prompted by the test script, first step was to click "mange content" and then create a collection. I named the collection and hit "create" and encountered an error message:

![screen shot 2018-06-19 at 3 32 23 pm](https://user-images.githubusercontent.com/25389954/41626043-a00b2528-73e0-11e8-9fb4-5b0339f70ea2.png)

However, the collection was actually created with no problems. Dru encountered the same problem when testing

**Comment by laura-alagna** [comment]
@mbklein david said to ping you on this one

**Comment by jenyoung** [comment]
I also got this notification.

**Comment by mbklein** [comment]
I've been experiencing this as well. It seems to be a race condition between the new collection and the web app trying to access it.

@carrickr Any ideas?

**Comment by jenyoung** [comment]
Also happening in production. testing in Firefox 60.0.1 (64-bit) on a Windows 10 PC.

**Comment by davidschober** [comment]
This will stay in ready as a known bug.

**Comment by davidschober** [comment]
@carrickr do you have any ideas?

**Comment by davidschober** [comment]
closingt as a known bug. There's a race condition.
