### ISSUE TITLE
Manage groups opens another tab

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#390]
When going to manage groups in AVR, clicking on the button for it opens another browser tab. 

Windows 10 PC, Chrome Version 66.0.3359.170 (Official Build) (64-bit)

**Comment by jenyoung** [comment]
Also happening in production. testing in Firefox 60.0.1 (64-bit) on a Windows 10 PC.

**Comment by davidschober** [comment]
Low priority as this was an existing bug. cc: @mbklein @carrickr

**Comment by mbklein** [comment]
This is by design in core Avalon; changing it is an enhancement, not a bug.

**Comment by davidschober** [comment]
Closing. We'll leave this as is for now.
