### ISSUE TITLE
Emails not being sent

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#391]
Email not being sent for these normal things on production

- [x] collection creation
- [x] batch upload success
- [ ] batch ingestion errors
- [ ] batch complete

**Comment by davidschober** [comment]
Received an email when the batch was kicked off, but I am not receiving any response when/ if a batch is complete. I am also not getting an email on collection creation. 

cc: @carrickr

**Comment by carrickr** [comment]
Also I answered David on slack, but just for clarity, it's not working due to a bunch of reasons that basically boil down to cron tasks need to be done differently on dockerized AWS infrastructure than they do on vanilla Avalon.

**Comment by davidschober** [comment]
@mbklein this got sorted, correct? I think this is really, really old. cc: @jenyoung

**Comment by davidschober** [comment]
@jenyoung reported again that emails are not being sent. I don't think is sorted out. We need to fix this so that end users have some feedback about batch going through. 

CC: @mbklein

**Comment by jenyoung** [comment]
@davidschober @mbklein we do get this email even if there are errors.

![2019-09-18_155335](https://user-images.githubusercontent.com/2250501/65185188-a4371400-da2c-11e9-97bd-24d1f9f6a0c1.png)

**Comment by davidschober** [comment]
That’s interesting so some emails are getting kicked off and not others. Now I’m thoroughly confused

**Comment by davidschober** [comment]
@jenyoung I get emails for collection creation. So it looks like it's just the batch errors/batch complete that aren't kicking off.
