### ISSUE TITLE
Herskovits collection count off

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#393]
Carolyn and David both see a count of 684 of Herskovits materials. I see a count of 685

![2018-06-21_114948](https://user-images.githubusercontent.com/2250501/41734083-86630688-754b-11e8-9108-11749693219b.png)

- need to investigate

**Comment by davidschober** [comment]
I tested and got the 684. This is a non-critical bug. 
![screen shot 2018-06-21 at 11 49 25 am](https://user-images.githubusercontent.com/4803230/41745767-b4393bc8-756d-11e8-9773-bef0bcd42425.png)

cc: @mbklein

**Comment by davidschober** [comment]
tested again and got 685.I think SOLR was being flaky. Closing.
