### ISSUE TITLE
[Avalon] Rebuild Cloudwatch Alerts for Avalon and Prod Stack

### ISSUE THREAD

**Issue by d-venckus** [nulib/avalon#395]

**Comment by d-venckus** [comment]
I have put together terraform code to create Cloudwatch Alarms for base stack components in thew new Stack-P environment, but I got stuck and couldn't easily find a way to assign them via code to the correct target instance ids.  This can normally be done at the time of component/instance creation, wherein the instance ids can be assigned to a variable in the terraform stanza.

MBK says he knows of a way for me to extract instance ids using remote_object.  I'm picking his brain to put everything together.

**Comment by Toputnal** [comment]
David and I setup monitoring for all production environments by hand.  devops/#319 has been created to track the work of writing the alerts in terraform code.

**Comment by d-venckus** [comment]
These are all in place.
