### ISSUE TITLE
During batch ingest, Terms of Use adds extraneous characters

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#403]
### Description

Importing via batch ingest adds extra brackets and quotation marks to the `Terms of Use` field.
Collection imported today (9/4/2018) - `Arnold Jacobs Master Class Audio Archives`

**Example:**
https://media.northwestern.edu/media_objects/3r074w361

["The audio recordings on this web site are from material in the collections of the Music Library of Northwestern University Libraries, are provided for use by its students, faculty and staff, and by other researchers visiting this site, for research consultation and scholarly purposes only. Further distribution and/or any commercial use of the audio recordings from this site is not permitted. Please contact musiclibrary@northwestern.edu with questions. COPYRIGHT UNDETERMINED"]

### Done looks like

- [ ] Batch ingest fixed so this no longer happens.
- [ ] Also, cleanup records with this issue #402

**Comment by davidschober** [comment]
@jenyoung can you test this on staging?

**Comment by davidschober** [comment]
@mbklein did you push this to prod? Can't remember. If so, can you move the issue?
