### ISSUE TITLE
Incorrect date should not validate

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#405]
### Description

During a recent batch ingest, invalid dates did not trigger an invalid date message and an email stating that the metadata was valid was sent.

### Done looks like:
- [ ] Don't validate incorrect dates and send an email saying so.

**Comment by davidschober** [comment]
@jenyoung do you know if this is still occurring? I think this got cleared up in a release.

**Comment by davidschober** [comment]
stale.
