### ISSUE TITLE
 link to LTI - protected content requires reload

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#411]
## Description

When linking to a an LTI- protected item in production, the user is passed through authentication, but the item page does not seem to be able to load the content. The start and end times are shown as 0:00--> 0:00. A page refresh loads the video properly

## To recreate

- go to an avalon test course video (without authenticating as a user <http://media.northwestern.edu/media_objects/3f4625424> private window
-  when challenged use auj5680 and authenticate
- see that video does not properly load 0:00--0:00
- reload
- watch this glorious masterpiece... no, wait, note the bug and try to figure out how to deal with the load issue.

![screen shot 2018-09-12 at 10 33 29 am](https://user-images.githubusercontent.com/4803230/45454603-1e122000-b6aa-11e8-93aa-a4216c273e16.png)
![screen shot 2018-09-12 at 10 33 38 am](https://user-images.githubusercontent.com/4803230/45454608-22d6d400-b6aa-11e8-9464-d2925b823f46.png)

cc: @mbklein @carrickr

**Comment by mbklein** [comment]
I've been unable to reproduce this – the video loads and plays just fine for me after the login redirect in Safari, Chrome, and Firefox.
