### ISSUE TITLE
Smoke test production, 11/1/2018

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#415]
Testing checklist for "Smoke" Testing, 11/1/2018

1. Search
2. Buttons function
3. Playback / Quality
4. Captions functioning
5. Create Playlist
6. Add Item to playlist / Add Clip to playlist
7. Ensure content migrated and is available

If you encounter any bugs, create an issue in https://github.com/nulib/avalon and add the "bug" label

**Comment by druparrish** [comment]
Smoke testing is done. Everything on the list is working, save for the 'captions function', which I cannot locate. 👎

**Comment by egilchrist** [comment]
Same results as Dru. Smoke testing is complete. I had the same issue with "captions function."
