### ISSUE TITLE
Can't ingest 4 films into Spec collection

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#422]
Erin and I have been trying and failing to ingest 2 works (total 4 MP4 files) into the `McCormick Library of Special Collections Audiovisual Collection` on and off for days now. 

On Staging:
- Batch accepted no errors email sent
- Only [one work](http://avr.stack.rdc-staging.library.northwestern.edu/media_objects/6969z115b) was ingested, no indication why the other one was not.

On Production:
- Upload metadata into dropbox (even copied into brand new spreadsheets, both Erin and I tried)
[Dawes_batch.xlsx](https://github.com/nulib/avalon/files/2857439/Dawes_batch.xlsx)
- No communication - no email, no errors, nada.
- After several attempts, deleted and reuploaded the MP4 files. Nothing changed, still not ingesting.

We are at a loss as to what we are missing. Other collections have gone in just fine (except for the AWS transcoding bug) in this same timeframe. This is a older project we are trying to close out this cycle.

**Comment by davidschober** [comment]
related to #421

@mbklein

**Comment by davidschober** [comment]
I was able to reproduce this with Jen. I went through normal troubleshooting with the spreadsheet.

**Comment by mbklein** [comment]
I'm looking into the reason for the ingest failure on Staging, but the production issue is easy: There's no collection linked to the `McCormick_Library_of_Special_Collections_Audiovisual_Collection` dropbox directory.

**Comment by mbklein** [comment]
The collection must have been renamed at some point, because its dropbox directory name is simply `Special_Collections`

**Comment by davidschober** [comment]
@mbklein I tried to help out here, but I don't have rights to change it.
