### ISSUE TITLE
Verify "move strategy" is in place in AVR

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#424]
## Description

We believe the "move strategy" is in place in AVR. We need to verify that the strategy is still in place after our most recent architecture changes.

## done looks like
- [x] verify master files are moved to preservation bucket

**Comment by davidschober** [comment]
We might be able to pick up this low hanging at the same time: https://github.com/nulib/next-generation-repository/issues/900

**Comment by laura-alagna** [comment]
@davidschober check for most recent file
