### ISSUE TITLE
Help! my batch disappeared

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#427]
### Severity

Is the production site running?
- [X] yes
- [ ] no

Are staff blocked from performing their work?
- [X] yes
- [ ] no

### Descriptive summary
I initiated an ingest on March 13 and received an email that the metadata was validated, no errors were found, and the batch was queued for ingest. However, the ingest has not gone through and I have not received an email about any errors (maybe this is related to #425 ?)

### Expected behavior
Ingest should work, or I should get an email letting me know what went wrong

### Actual behavior
No idea what is happening :(

### Steps to reproduce the behavior
My ingest is for the Leigh Bienen Videos collection. The batch_manifest.xlsx seems to have disappeared from the dropbox (is it supposed to do that???) so I am attaching below

**Comment by laura-alagna** [comment]
[batch_manifest.xlsx](https://github.com/nulib/avalon/files/2979994/batch_manifest.xlsx)

**Comment by davidschober** [comment]
cc @mbklein Making sure you saw this come across

**Comment by laura-alagna** [comment]
this is fixed, thanks @mbklein !
