### ISSUE TITLE
Verify necessary users are in AWS Avalon groups

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#43]
- [x] David dsc712
- [x] jim jre700
- [x] David V. drv460
- [ ] Carrick Rogers
- [ ] Chris Syverson
- [ ] karen d
- [ ] brendan q.

**Comment by rtrautve1** [comment]
I will send this list to matt stork to add remaining users into the appropriate ADS group giving permissions to the NexGen AWS account

**Comment by rtrautve1** [comment]
@bmquinn @carrickr @csyversen @kdid 
please go to  aws.northwestern.edu/  and confirm you can log into  NexGen  AWS workspace - remember to select  N. Virginia as the region - and you should be able to get in and see MBK work

**Comment by rtrautve1** [comment]
@davidschober   - FYi - moving this to review - Matt S has added all into ADS group and they should test to confirm access
