### ISSUE TITLE
Can't select anything

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#432]
### Description
In avalon I will select items (that I am the manager of) then click "manage selected items"...and I get a "no items selected" message! So I can't actually make edits to more than one item at a time :/

<img width="1175" alt="Screen Shot 2019-04-01 at 1 17 23 PM" src="https://user-images.githubusercontent.com/25389954/55436258-d1206900-5569-11e9-9487-78619795b142.png">

### To recreate
I logged in as aum1701 and tried to select items and manage, and the same thing happened, so it isn't just me

**Comment by davidschober** [comment]
I was able to recreate this as well.

**Comment by mbklein** [comment]
After some struggling with my dev environment, I've reproduced the issue locally as well.

**Comment by mbklein** [comment]
I pushed a fix to staging; please verify and we can deploy it to prod.

**Comment by davidschober** [comment]
worked for me. @laura-alagna do you want to check with your account as well?

**Comment by laura-alagna** [comment]
agreed, the fix on staging looks good @mbklein !

**Comment by davidschober** [comment]
Let's set this fix free! Be free bug fix, be free!
