### ISSUE TITLE
Create local  repository to customize / push to Amazon

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#45]
@mbklein @adamjarling  has started to work on customizing Avalon 6.x for NU. We need a repo for him to push to (and you to pull from ) for http://avalon.repo.rdc.library.northwestern.edu. 

Can you take this and run with it?

**Comment by davidschober** [comment]
closed. @adamjarling can you drop the URL in here?

**Comment by adamjarling** [comment]
@davidschober For now, here is where we're pushing the skinning code, but this will likely change by end of week:  https://github.com/nulib/avalon/tree/nu-avalon-skin
