### ISSUE TITLE
Determine How To Connect Images-P and the Amazon Stack

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#47]
My understanding (correct me if I'm wrong @mbklein) is that right now you need a VPN to connect into AWS machines.  To load the data into the Fedora up on AWS, I assume we don't want to install a VPN on avalon-prod, rather we want to either set up some kind of keypair or else temporarily expose our Amazon Fedora to avalon-prod while we push data.

**Comment by davidschober** [comment]
@carrickr is this supposed to be an avalon one or is this a more general issue?

**Comment by davidschober** [comment]
@carrickr this is abandoned, correct? closing.
