### ISSUE TITLE
Test ffv1 format in Avalon AWS

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#58]
## Description

the production team has proposed using the [ffv1](https://en.wikipedia.org/wiki/FFV1)  standard as a digitization standard for ?analog? videos. We need to test whether or not Avalon in AWS can ingest these without issue

## Done looks like

- [x] an ffv1 video is created and a link is attached to the comments below
- [x]  A video is uploaded to [avalon in AWS](http://avalon.repo.rdc.library.northwestern.edu)

**Comment by jyocumNU** [comment]
Uploaded ffv1 file.  Looks like it worked. 
http://avalon.repo.rdc.library.northwestern.edu/media_objects/x920fw84d

**Comment by davidschober** [comment]
Awesome thank @jyocumNU @mbklein It looks like AWS transcoder handles ffv1 out of the box. They are pretty large though (1 minute was ~700megs) uncompressed. So we will definitely not want to store files like this longterm on s3.
