### ISSUE TITLE
Ensure we have access to cost allocation tags

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#59]
Bob,

We don't seem to have cost-allocation tags. Can we make sure that @mbklein @ccaizzi and I have access to this:

https://console.aws.amazon.com/billing/home?region=us-east-1#/preferences/tags

**Comment by rtrautve1** [comment]
Ok. I thought MBK could see it.  I never got a response from the DLT folks (who are our vendor for AWS) concerning the cost-allocation tags that MBK was using. So I'll get Carolyn access and then follow up again with DLT on the cost allocation tags - these really are important as you know if we have multiple projects in the same space - we need to be able to distinguish the costs between different project. thanks for the follow up on this

**Comment by ccaizzi** [comment]
Michael Hannon as a contact.

**Comment by rtrautve1** [comment]
abandoned.  Tags are preset by DLT
