### ISSUE TITLE
Streams not working on Chrome

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#67]
## Description 

Technical support
Comment
most of the master classes do not load at all for me, in general I press the play button and nothing happens, I used to be able to listen to the master classes before but recently the application is not working for me. Thanks for your help.
Received
2017-05-22T21:04:58-05:00

**Comment by davidschober** [comment]
![settings - content settings 2017-05-23 10-30-40](https://cloud.githubusercontent.com/assets/4803230/26362436/8c4ece12-3fa3-11e7-98c7-f08277f68975.png)

Possible work around

**Comment by davidschober** [comment]
@Nic4Images It looks like chrome is blocking flash and has a bug that isn't giving a user a warning. To fix this a user should go to preferences:

![screen shot 2017-05-23 at 10 44 18 am](https://cloud.githubusercontent.com/assets/4803230/26362825/d0f12a14-3fa4-11e7-844d-5b6d3a8a42d5.png)

Click "show advanced settings"

Click "Privacy --> Content Settings"
![screen shot 2017-05-23 at 10 45 55 am](https://cloud.githubusercontent.com/assets/4803230/26362962/292591b6-3fa5-11e7-9cf9-fb348a4cb065.png)


click "Flash --> Manage Exceptions"

![screen shot 2017-05-23 at 10 45 20 am](https://cloud.githubusercontent.com/assets/4803230/26362943/1d1ac08a-3fa5-11e7-997d-ce03e6efc137.png)


add "media.northwestern.edu"

**Comment by davidschober** [comment]
@Nic4Images do you want to try that out? @carrickr that looks like the workaround for now, correct?

**Comment by Nic4Images** [comment]
I did all of this and now it is playing in Chrome.

**Comment by Nic4Images** [comment]
Note from Juan : I am on windows 10 on my PC, your suggestion made me try on my phone which can use safari, this indeed works just fine.

**Comment by davidschober** [comment]
@Nic4Images per our discussion. Let's put this on the page. Ideally it should go on the item page as users come at this from all around. 

"Having trouble streaming with Chrome? [Find out how to unblock Flash Player.](link to doc)"

@Nic4Images can you verify that ^^^ is good with you?
