### ISSUE TITLE
ensure that ALMA bib import IDs using Primo IDs are mapped correctly

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#78]
For Course Reserves, they are importing into AVR using the Permalink ID from Primo instead of the Bib ALMA number. It works, that's fine. But that identifier is being mapped to type="other" - it should be mapped to "local" and display as Catalog Key instead.

## **Example:**

**What it looks like now:**
AVR: https://media.northwestern.edu/media_objects/numedia:29441

Primo Permalink: http://search.library.northwestern.edu/NULV:library_resources:01NWU_ALMA21554504630002441

Other identifier: 21554504630002441
type="other"

**What it should look like:**

AVR: https://media.northwestern.edu/media_objects/numedia:29441

Primo Permalink: http://search.library.northwestern.edu/NULV:library_resources:01NWU_ALMA21554504630002441

Catalog Key: 21554504630002441
type="local"

## Done looks like:

- display changed to Catalog Key from "Other Identifier"
- type changed to "local" from "other"

**Comment by davidschober** [comment]
@jenyoung This looks like data cleanup. Nothing here holds up launch, correct?

**Comment by davidschober** [comment]
per discussion with Jen, this may be a workflow issue. @jenyoung to investigate and cleanup a bit more

**Comment by jenyoung** [comment]
@davidschober this is not the same issue as the other one. These are not being mapped correctly.

**Comment by jenyoung** [comment]
@davidschober this is not urgent but should be cleaned up and corrected in the mapping at some point.

**Comment by jenyoung** [comment]
@davidschober will this be corrected soon? new titles are being ingested with this incorrect information.

**Comment by davidschober** [comment]
@carrickr can you slate these for the next couple of weeks?

**Comment by davidschober** [comment]
@jenyoung This obviously fell off the docket. Can we discuss how critical this is? I'm trying to figure out if we should dedicate resources to it or if, given it's a small set of data, we can take it as a known issue.

**Comment by davidschober** [comment]
stale. We will handle with a future migration.
