### ISSUE TITLE
Train Carrick and Devops/ Write procedures for outages

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#79]
## Description 

With MBK in Australia during the first week of our live Avalon in AWS cloud environment, it's critical that we have procedures in place for how to bring the system back up in case of emergency. We need to have a handle on what to kick, when, etc.

## Done looks like

- [x] Documentation is written and published in the [repodev wiki](https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-Technical-Documentation#what-to-do-when-things-are-bad)
- [x] The wiki has links to all information needed so no one is locked out
- [x] any necessary keys, etc, are locked away where they need to be and we have documented where to find them
- [x] @Toputnal @carrickr @d-venckus know how to respond to an emergency. 
- [x] review and add screenshots to [outage workflow](https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-AWS-Overview-and-Outage-Information)

**Comment by ccaizzi** [comment]
@mbklein @Toputnal @carrickr @d-venckus 
Actually, can you all meet up this week and get this done please.

**Comment by carrickr** [comment]
Meeting has been scheduled for Thursday afternoon

**Comment by davidschober** [comment]
Thanks! (can I get an invite)

**Comment by davidschober** [comment]
@Toputnal and @d-venckus can you review @carrickr 's notes, and help clean up any misunderstanding?

**Comment by davidschober** [comment]
@mbklein have we published the keys to the lockbox?

**Comment by davidschober** [comment]
Procedures here. We still need to clean them up

https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-AWS-Overview-and-Outage-Information

And add screenshots. I may edit them into the general technical docs.

**Comment by carrickr** [comment]
I'm going to do a brief overview for the other devs on Friday so they know what is happening

**Comment by egspoony** [comment]
@Toputnal @d-venckus to look at the documentation and take screenshots to add to the documentation.

**Comment by Toputnal** [comment]
I have added some basic screenshots where instructions were available.  Please let me know if/where additional screenshots  may be needed.  @carrickr @davidschober @d-venckus @mbklein @MarekBabala https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-AWS-Overview-and-Outage-Information

**Comment by davidschober** [comment]
I'm going review this and kick off issues for the TODOs in here. @carrickr or @mbklein  do you want to take a  quick glance?

**Comment by d-venckus** [comment]
Closing, will test.
