### ISSUE TITLE
rewrite docs for uploading content using cyberduck, etc

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#81]
## Description 

Write docs for uploading content to Avalon. Ideally I can steal these from @jenyoung and @Nic4Images current docs and tweak them for use with Cyberduck/ Avalon 6.x

## Done looks like

Docs are written and published in wiki

**Comment by ccaizzi** [comment]
@mbklein will generate 1 click scripts for CB for Molly, Cecile, and all of us by Tuesday, June 6.

**Comment by davidschober** [comment]
doen https://github.com/nulib/repodev_planning_and_docs/wiki/AVR-Collection-Administrator-and-Service-Manager
