### ISSUE TITLE
Access Control cleanup for Course Reserves/MMLC

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#83]
## Issue

Noticed that a Course was attached to almost 1000 items during migration. This brought up the issue of old courses still being attached long after the course is over. Want to automate purging off course attachments every quarter. Will also require 

## Example from Molly:

I’ve wondered if some Access Control clean up might, or could, happen with this migration.  For a good example of what I mean, please see the Access Control page for Moneyball <https://avalonweb2p.library.northwestern.edu/media_objects/numedia:10910/edit> - a long history of courses listed, and a great many are garbled alphanumeric listings.  Is the Access Control course history to be fully retained in the AVR, or maybe partially purged to make listings like this less cumbersome?  

## Done Looks Like

- [ ] Develop plan for purging old courses and their attachments to videos once course/need is over
- [ ] create general group and/or collection (non-public, course reserves/mmlc only)
- [ ] Write script and/or feature to move videos to general group/collection after removal from a course, ideally every quarter
- [ ] document procedure
- [ ] train course reserves/mmlc staff

**Comment by jenyoung** [comment]
This are screenshots from Molly's Example

![2017-06-06_112635](https://user-images.githubusercontent.com/2250501/26840286-410e0018-4aab-11e7-8060-5e3f4c85b619.jpg)

![2017-06-06_112651](https://user-images.githubusercontent.com/2250501/26840292-44ebef4c-4aab-11e7-8a63-dfcc1802d268.jpg)

![2017-06-06_112706](https://user-images.githubusercontent.com/2250501/26840294-47353fa6-4aab-11e7-8019-b065e3a7489d.jpg)

**Comment by mbklein** [comment]
Doable, but requires some thought. We should have a delete trigger on the Course database record that deletes it from all relevant MasterFiles. Purging based on prefix (e.g., `2017WI`) is easy enough, but we'll need to write code to update all the MediaObjects.

**Comment by davidschober** [comment]
k. I'm pushing this to post golive @mbklein and @carrickr

**Comment by davidschober** [comment]
@mbklein this looks very stale. Can you verify that this is still valid?

**Comment by davidschober** [comment]
Did this get cleaned up with the other alma work we did?
