### ISSUE TITLE
No media associated with items ingested with batch

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#84]
I uploaded the test batch using the batch upload via cyberduck and did not get any errors (batch_manifest.xlsx.error is empty)

However, when I search for the uploaded videos, the metadata is there but no videos. Instead there's an error message "no media associated with this item"

<img width="1169" alt="screen shot 2017-06-06 at 2 52 27 pm" src="https://user-images.githubusercontent.com/25389954/26849257-124ddd52-4ac9-11e7-9ead-8616953b0275.png">

**Comment by laura-alagna** [comment]
I'm told this is a transcoding thing, I changed the batch spreadsheet so that it would not skip transcoding and reingested...no change

**Comment by jenyoung** [comment]
closing.
