### ISSUE TITLE
Voyager permalinks in records are broken

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#85]
## Issue
Older metadata records in AVR contain links in the ```Summary``` part of the bib record but are using the old Voyager number in the URL which fails. The URL should be using the ALMA numbers. 

**Example:**
http://avalon.repo.rdc.library.northwestern.edu/media_objects/pk02c977h

**OLD:**
http://search.library.northwestern.edu/NULV:voyager4351748
http://search.library.northwestern.edu/NULV:Libraryresources:voyager3003517

**NEW:**
http://search.library.northwestern.edu/NULV:library_resources:01NWU_ALMA21399159780002441

## Done Looks Llike

- [ ] figure out how to transform Voyager Permalinks to ALMA Permalinks

to find these in Avalon search "http://search.library.northwestern.edu"

**Comment by davidschober** [comment]
is there a way to do this automatically?

**Comment by davidschober** [comment]
This isn't a new problem. This surfaced as part of the migration.

**Comment by davidschober** [comment]
@jenyoung to find new examples, and possibly deal with this as a workflow issue.

**Comment by davidschober** [comment]
@jenyoung I think we forgot to close this. closing now.
