### ISSUE TITLE
Changes to make to testing script

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#86]
## Keeping track of changes to make to testing script here

- ```skip transcoding``` should not be used and does not work in AWS
-- change batch spreadsheet to reflect that
- update server information on first tab
- user ids setup
- make clear that non-admin user tests "hidden from search results"
- make clear when to use the different logins with different roles/permissions

**Comment by laura-alagna** [comment]
There's a few that are confusing to me:
row 112: "Setting begin and end dates to invalid errors shows an error message" - not sure how this is different from the one above it
row 116: "User can change the time range of an item in a playlist" - not sure what this means or how to do it

**Comment by egilchrist** [comment]
There are a few things confusing to me to:
1) In the Bulk Issues column, it's difficult to tell what is being done as admin or as "generic user tester"
2) When you sign in as generic user tester, it still says sign in (can't tell if you logged in)
3) In 9 search/playback, I think you move from user tester for items 1-2, but then you create a thumbnail as an admin
4) I'm unclear what the difference is between "Setting begin and end dates to invalid errors shows an error message" vs "Setting begin and end dates to invalid values does not throw errors" - which could be why Laura and I couldn't get it to throw an error.

**Comment by jenyoung** [comment]
change link to this http://www.avalonmediasystem.org/downloads/DemoFixturesBatch.tar.gz for "demo ingest package"

add .vtt captions file to test batch

**Comment by jenyoung** [comment]
add instructions to delete test collections

add mbk's test fixtures

**Comment by jenyoung** [comment]
newer script from Big Avalon https://northwestern.app.box.com/files/0/f/32661284132/Testing

**Comment by jenyoung** [comment]
possible story https://github.com/avalonmediasystem/avalon/issues/2166

**Comment by davidschober** [comment]
@jenyoung this got done by Mathew... I'll close for now.
