### ISSUE TITLE
Items marked as "hidden from search results" still showing in search results

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#87]
I used bulk edit on two items (http://avalon.repo.rdc.library.northwestern.edu/media_objects/6w924b96s and http://avalon.repo.rdc.library.northwestern.edu/media_objects/mc87pq505) to test the access controls. I hid both from search results but both are still showing up when I search. 

notes: 
I waited 10 minutes for the access change to go into effect
I logged out and back in
...no changes, still in search results.

**Comment by jenyoung** [comment]
@mbklein @carrickr Possible Big Avalon related issues 

https://github.com/avalonmediasystem/avalon/issues/1758
https://github.com/avalonmediasystem/avalon/pull/2005

**Comment by jenyoung** [comment]
logging in as non-admin solved the issue. closing.
