### ISSUE TITLE
Update RDC production workflow document for AVR 6/CyberDuck

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#89]
Update/combine these box notes and move to our [github wiki](https://github.com/nulib/repodev_planning_and_docs/wiki#avr)
https://northwestern.app.box.com/notes/69814497621
https://northwestern.app.box.com/notes/36791411598
https://northwestern.app.box.com/notes/20187969035
https://northwestern.app.box.com/notes/178735601232

Maybe create a separate document for LTI/Canvas procedures

- [x] document cyberduck 
- [x] document ingestion procedures

related #81

**Comment by davidschober** [comment]
@jenyoung @Nic4Images @egilchrist It looks like some of these docs are quite old. I'm glad to help format for the wiki to speed things along, but I want you to own the process. Can you take a look at the docs and update.

**Comment by davidschober** [comment]
@druparrish, @egilchrist , @jenyoung is this still active? Are you comfortable with the docs we have? If so, let's close this as stale.

**Comment by davidschober** [comment]
@jenyoung @laura-alagna I'm culling some very stale issues. I think this one got done via our "big book" work and has just kind of been hanging around. I'm going to close it for now. Feel free to reopen if I'm misunderstanding something. 

I marked the old box notes as "DEPRECATED". If you're OK with it, maybe we should just delete?
