### ISSUE TITLE
Adding new public collections to Avalon HP

### ISSUE THREAD

**Issue by davidschober** [nulib/avalon#9]
## DONE
New collection added to the HP of media.library.northwestern.edu

## Email from Laura

As I mentioned yesterday to Michael and Chris, I have been working on an audio collection of interviews with African authors from the Herskovitz Library. It’s nearly ready to be imported to AVR, and I was wondering if it would be possible to have a link to it on the homepage like the Marcellus and Football collections. This collection is significant, and I think it would score a lot of points with Esmeralda to have be quite visible.   Michael and Chris told me that it’s possible to adjust that page however we want – I’m hoping that it’s an easy task and that there’s time for one of the developers to do it.

Let me know if it’s feasible, and what the time frame would be.  I am just waiting for Jen or Nicole to sign off on the metadata to import the collection.

Thanks!
Laura

**Comment by davidschober** [comment]
@Nic4Images can you update this issue when you have the collection ready to go?

**Comment by Nic4Images** [comment]
@davidschober yes!

**Comment by jenyoung** [comment]
the metadata is good to go. just waiting on dropbox issue to be sorted

**Comment by laura-alagna** [comment]
@davidschober @csyversen @mbklein The collection is ingested and ready in Avalon. See [Herskovits Library of African Studies Audio Collection](https://media.northwestern.edu/catalog?f%5Bcollection_ssim%5D%5B%5D=Herskovits+Library+of+African+Studies+Audio+Collection)

**Comment by davidschober** [comment]
cool. Moving to ready.

**Comment by davidschober** [comment]
@mbklein or @csyversen can you show @carrickr how to do this next week?

**Comment by davidschober** [comment]
@mbklein this has been hanging around for a while, can you grab it?

**Comment by mbklein** [comment]
@adamjarling knows how to make this happen.

**Comment by adamjarling** [comment]
There's a pull request in place to add this collection to the homepage's Featured Collection listing.
