### ISSUE TITLE
Videos in my playlist won't play

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#90]
I made a playlist: http://avalon.repo.rdc.library.northwestern.edu/playlists/1 
Videos will not play from the playlist (with autoplay on and autoplay off)

**Comment by laura-alagna** [comment]
Update: nothing is playing, not just the playlist

**Comment by jenyoung** [comment]
@laura-alagna can you take a look at this tomorrow afternoon after the derivatives are done please

**Comment by laura-alagna** [comment]
@mbklein @carrickr everything works now, closing #90
