### ISSUE TITLE
MODS contains extra empty fields

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#92]
Just like https://github.com/avalonmediasystem/avalon/issues/1935 seeing lots of extra empty elements

Example
http://avalon.repo.rdc.library.northwestern.edu/media_objects/j6731382c/content/descMetadata

Looks like it is an adding an empty element for each filled in element. Maybe creating a duplicative MODS record inside.
![2017-06-06_173552](https://user-images.githubusercontent.com/2250501/26855120-f3c8d93e-4ade-11e7-99f6-7bd94ca1983b.jpg)
![2017-06-06_173655](https://user-images.githubusercontent.com/2250501/26855124-f6d530be-4ade-11e7-9572-bcd6f3f60c9e.jpg)
![2017-06-06_173720](https://user-images.githubusercontent.com/2250501/26855132-f957c162-4ade-11e7-8744-58354c95f2fa.jpg)

**Comment by jenyoung** [comment]
But I am not seeing this on every record.

**Comment by jenyoung** [comment]
this is supposed to be fixed in Big Avalon. How can we apply the fix?

**Comment by mbklein** [comment]
Did you find an issue in Avalon Core that relates to this? If it's been resolved with a PR, I can pull it over.

**Comment by davidschober** [comment]
avalonmediasystem#1935

**Comment by davidschober** [comment]
@mbklein I don't know if you want to pull it over, or wait for the official 6.1 release. I think we should wait for 6.1

**Comment by davidschober** [comment]
Note this is upstream we can pull it post golive when we merge in 6.1

**Comment by davidschober** [comment]
6.1 dropped, we will grab this when we upgrade in a couple of weeks. @mbklein

**Comment by jenyoung** [comment]
@mbklein @davidschober this is still a problem on our current 6.1 instance - see https://media.northwestern.edu/media_objects/ft848q651/content/descMetadata

**Comment by davidschober** [comment]
@jenyoung can you check on staging now? I think 6.2 may have cleared this up.
