### ISSUE TITLE
Fedora 4 PID populating Bibliographic ID when editing record 

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#93]
Records I pull up to edit are being populated with the Fedora 4 PID in the Bib ID field in the Resource Description Form

![2017-06-06_174140](https://user-images.githubusercontent.com/2250501/26855307-ca6c8314-4adf-11e7-88a9-54539ebeef94.jpg)

**Comment by davidschober** [comment]
@jenyoung can you put in a couple of URLs or is it everything?

**Comment by mbklein** [comment]
I know why this is happening, and I'm trying to figure out the best way around it.

**Comment by davidschober** [comment]
I think this looks fixed!
