### ISSUE TITLE
Editing record to add a Note adds an empty Contents

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#94]
Cleaning up some Note elements that did not properly have a Note Type. Adding the Note Type in the Resource Description Form and a Contents note is generated.

Resource Description Form
![2017-06-06_175959](https://user-images.githubusercontent.com/2250501/26855672-0164a9a8-4ae2-11e7-887d-9f38d1c19eb0.jpg)

Record View
![2017-06-06_175615](https://user-images.githubusercontent.com/2250501/26855636-d11d228e-4ae1-11e7-8290-0366bcc8dc95.jpg)

MODS view
![2017-06-06_175654](https://user-images.githubusercontent.com/2250501/26855640-d4fc7a58-4ae1-11e7-97a4-7414c1f9468e.jpg)

**Comment by davidschober** [comment]
@jenyoung can you check to see if this is occurring on pawpaw or any IU instance? If so, let's close this and kick off a big bug.

**Comment by jenyoung** [comment]
Bug not on spruce. Also, no longer on the record I initially found the bug on. Going to close.
