### ISSUE TITLE
Make plan with Course Reserves/MMLC for transcripts in Summary field

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#95]
Course Reserves/MMLC have added transcript information to the ```Summary``` field. Sometimes this breaks the field - we had to turn off indexing in Solr for ```Summary``` to be able to migrate these items.

## Done looks like

- schedule meeting with Molly, Cecile-Anne, Jen, others?
- develop plan for transcript information (```related item``` most likely)
- edit records to move transcripts to appropriate area
- turn indexing on in Solr for ```Summary```

**Comment by mbklein** [comment]
@jenyoung I think transcripts can stay in the summary field. I can split large MODS fields into multiple solr fields for indexing. Solr doesn't mind huge documents; just huge fields. It won't affect display, and it'll keep all the text indexed for searching.

**Comment by davidschober** [comment]
@mbklein That sounds like a great plan. Is this something we should do now or post golive?  If post, can you pull it into the post-golive milestone.

**Comment by davidschober** [comment]
@jenyoung will talk to molly about transcripts and whether they should live in a different field. This would require we move the old data. I'm going to move this post go-live. This would likely be a human.

**Comment by davidschober** [comment]
@mbklein did you end up splitting summary into multiple solr fields for indexing?

**Comment by davidschober** [comment]
@jenyoung I'm closing it looks like we decided to keep transcripts in the summary field for now.
