### ISSUE TITLE
Can't delete a Notes field

### ISSUE THREAD

**Issue by jenyoung** [nulib/avalon#96]
I was testing other note types to see if  #94 only pertains to when you add a local note type. It doesn't matter what type of note. Great. So then I was editing my record to remove the notes field and it doesn't take. 

record in question:
http://avalon.repo.rdc.library.northwestern.edu/media_objects/5h73pw12z

**Comment by jenyoung** [comment]
Big Avalon bug https://github.com/avalonmediasystem/avalon/issues/1970

**Comment by mbklein** [comment]
I knew I'd seen something similar. I'll merge that in.

**Comment by davidschober** [comment]
@mbklein let us know when we should test this.

**Comment by davidschober** [comment]
@jenyoung can you test and close?

**Comment by davidschober** [comment]
Tested. I was able to remove notes field. @jenyoung can you confirm and reopen if necessary?
