### ISSUE TITLE
Get Some Audio and Video That Stream for Testing

### ISSUE THREAD

**Issue by carrickr** [nulib/avalon#98]
Streaming Audio:

http://avalon.repo.rdc.library.northwestern.edu/media_objects/pk02c977h
http://avalon.repo.rdc.library.northwestern.edu/media_objects/2b88qc23w
http://avalon.repo.rdc.library.northwestern.edu/media_objects/2j62s4898

Streaming Video:

http://avalon.repo.rdc.library.northwestern.edu/media_objects/c534fn97v (Section 2 only attached currently, Section 1 is 0:00)
http://avalon.repo.rdc.library.northwestern.edu/media_objects/0r967372b (medium and high quality only)
http://avalon.repo.rdc.library.northwestern.edu/media_objects/3197xm08n (My two favorite teams are Michigan and whoever plays Ohio State)

@jenyoung Let me know if you'd like more.  Also I did start every item and get at least some of it playing.  If a few sections in it stops, it's probably just due to the fact we only have 41% of the derivatives attached right now.

**Comment by ccaizzi** [comment]
We can close this now.
