### ISSUE TITLE
LTI add external group shows "Avalon Testing" twice

### ISSUE THREAD

**Issue by laura-alagna** [nulib/avalon#99]
<img width="1231" alt="screen shot 2017-06-07 at 2 26 23 pm" src="https://user-images.githubusercontent.com/25389954/26897222-647d6d26-4b8d-11e7-8241-ad5619640b35.png">

**Comment by mbklein** [comment]
Avalon Testing was in the database twice with two different context IDs. No idea how that happened, but it shouldn't have. I deleted one of them and this seems fine now.
